### ISSUE TITLE
Need help to address issue - Uprobe works in libbpf and Uprobe-tracer, but libbpf-rs failed!

### ISSUE THREAD

**Issue by cuserdzy** [libbpf/libbpf-rs#1020]
Hi, I'm facing a very strange issue:

Currently I'm working on a Linux based OS, similar with Android, but I think this issue is not related with OS itself since using libbpf-bootstrap or writing the tracer to /sys/kernel/debug/tracing/uprobe_events both work.

My kern space code is very simple, just print log, like:
```c
SEC("uprobe")
int BPF_KPROBE(func_a)
{
  bpf_printk("func_a called");

  return 0;
}
```

And the user space code just attached the object to a library, only specific the offset, without function symbol name:
```c
	skel->links.uprobe_func_a = bpf_program__attach_uprobe(skel->progs.uprobe_func_a,
                false,
		-1,
                 lib_path,
                0x15f20);
```

Above code works fine and the kernel log can be print.

But while use libbpf-rs (I have tested both 0.23 and 0.24), my code:
```rust
    func_a_hooker_skel.links.func_a = Some(
        func_a_hooker_skel
            .progs
            .func_a
            .attach_uprobe(false, -1, lib_path, 0x15f20)
            .unwrap(),
    );
```

The kernel log won't print, but the rust program runs well without error!

I have tried to address the issue for several days, but only found while using libbpf, the `bpftool link` will show a link associated with the loaded prog, like:

```
1: perf_event  prog 77
```

But while using libbpf-rs, no link showed up.

And even more, I checked /proc/<pid>/mem and dumped the hex byte at hooked address, the libbpf rewrite the address to `a0 00 20 d4` which is BRK instruction, but libbpf-rs didn't rewrite the address! I think this is the reason why hook not triggered but I can't address the issue because no error logs.

Sorry for no reproducible project on pure Linux... but any help is appreciate, Thanks!

**Comment by danobi** [comment]
Hi, maybe check if your rust code is holding onto the link? When link is dropped everything gets detached. A common error is to do something like `let _ = prog.attach();`.

Would be easier to help if you could provide a reproducer.

**Comment by cuserdzy** [comment]
> Hi, maybe check if your rust code is holding onto the link? When link is dropped everything gets detached. A common error is to do something like `let _ = prog.attach();`.
> 
> Would be easier to help if you could provide a reproducer.

Hi @danobi 

Yes I indeed called `attach` function:

<img width="625" alt="image" src="https://github.com/user-attachments/assets/adfcf7c7-23c4-4f14-aa63-06bb284abd3e">

But no link showed up

I have attached the C and Rust source code which I used to do test:
[demo.zip](https://github.com/user-attachments/files/17939447/demo.zip)

**Comment by danobi** [comment]
Try removing the `dummy_uprobe_hooker_skel.attach()` and seeing if that changes anything. The later attach() may be overwriting the previous. Doesn't seem necessary to attach twice.

**Comment by cuserdzy** [comment]
Yes after I remove `dummy_uprobe_hooker_skel.attach()` the uprobe works, appreciated for your help!!

I added `dummy_uprobe_hooker_skel.attach()` because in libbpf-boorstrap uprobe example (https://github.com/libbpf/libbpf-bootstrap/blob/9b61dedabee54f7f3cef95b3e8d8ae338a5a2cb0/examples/c/uprobe.c#L25)
I found it called `uprobe_bpf__attach` after called `bpf_program__attach_uprobe_opts`
<img width="770" alt="image" src="https://github.com/user-attachments/assets/90e283d2-fa7d-4d95-a418-ea94a263ccbe">

In my C test demo, the generated code will be:
<img width="650" alt="image" src="https://github.com/user-attachments/assets/d13686bf-3a93-4770-a9f5-097c4e02d9d6">

In libbpf-rs, the generated code will be:

<img width="970" alt="image" src="https://github.com/user-attachments/assets/19ef7472-805d-440e-b007-cc5f36dffb06">

So I called `attach()` function attach uprobes

**Comment by danielocfb** [comment]
I suppose this is resolved now? Closing accordingly. If not please feel free to reopen. Thanks for chiming in, @danobi.
