### ISSUE TITLE
C struct exported to skel.rs

### ISSUE THREAD

**Issue by chentao-kernel** [libbpf/libbpf-rs#1024]
Hi guys, i use the libbpf-bootstrap, but the struct conn_ctrl_connect_t seems no exported to net.skel.rs, and the other struct seems ok

<img width="742" alt="image" src="https://github.com/user-attachments/assets/b56b2b2f-ba92-4f4e-8980-4db637ec4783">

the source code:
https://github.com/chentao-kernel/libbpf-bootstrap/tree/master/examples/rust/xtrace

**Comment by danielocfb** [comment]
If it's not contained in the BTF you have to nudge the compiler to do that by declaring a dummy:
```patch
--- src/bpf/net.bpf.c
+++ src/bpf/net.bpf.c
@@ -32,6 +32,10 @@ const uint64_t USER_HZ = 100;
 const int ConnStatsBytesThreshold = 131072;
 const int ConnStatsPacketsThreshold = 128;

+// Dummy instance to get skeleton to generate definition for `struct
+// conn_ctrl_event_t`
+struct conn_ctrl_event_t _event = {};
+
 #define ntohs(x) (u16) __builtin_bswap16((u16)x)

 #ifdef NET_TEST
```

**Comment by chentao-kernel** [comment]
> If it's not contained in the BTF you have to nudge the compiler to do that by declaring a dummy:
> 
> ```diff
> --- src/bpf/net.bpf.c
> +++ src/bpf/net.bpf.c
> @@ -32,6 +32,10 @@ const uint64_t USER_HZ = 100;
>  const int ConnStatsBytesThreshold = 131072;
>  const int ConnStatsPacketsThreshold = 128;
> 
> +// Dummy instance to get skeleton to generate definition for `struct
> +// conn_ctrl_event_t`
> +struct conn_ctrl_event_t _event = {};
> +
>  #define ntohs(x) (u16) __builtin_bswap16((u16)x)
> 
>  #ifdef NET_TEST
> ```

Hi danielocfb, it seems ok with your mehtod, thanks a lot!
