### ISSUE TITLE
bpf_dynptr_copy ?

### ISSUE THREAD

**Issue by mattfysh** [libbpf/libbpf-rs#1041]
.

**Comment by danielocfb** [comment]
I am not familiar with dynptr/skb APIs, and generally that sounds more like a general BPF question than anything `libbpf-rs` specific. Would probably be best to check the kernel selftests for examples and if you can't find anything there to inquire with the BPF mailing list itself, at least that would be my recommendation.

**Comment by mattfysh** [comment]
thanks @danielocfb - i found this from the kernel mailing list: https://lore.kernel.org/bpf/CAJnrk1bSXgpPLK-e-fu6UyFypAY=EGmeDh-7ftj3ekMwf4DNuw@mail.gmail.com/ ... sounds like `bpf_dynptr_copy` was planned but not yet implemented

are there any examples of using libbpf-rs for pcap writing?

the hurdles i've found so far are related to packet sizes varying wildly on cgroup_skb types (eg. up to 10000 for jumbo frames) copying into the ebpf stack is not supported due to the 512 stack limit

i was previously using `bpf_ringbuf_reserve` but it requires statically known reserve size at compile time, so would only work by reserving 10000 each time, even for small packets of 20 or less bytes

**Comment by anakryiko** [comment]
@mattfysh it is planned (in the kernel, libbpf-rs has nothing to do with this) to implement generic bpf_dynptr_copy(). Meanwhile, I wrote a demo on how this can be achieved: https://github.com/libbpf/libbpf-bootstrap/pull/287/files if you'd like an inspiration
