### ISSUE TITLE
Add the ability to iterate over links

### ISSUE THREAD

**Issue by willfindlay** [libbpf/libbpf-rs#105]
As of #90 we now have the ability to iterate over maps and programs using the underlying Object and OpenObject. It would be nice to be able to do the same thing for Links. That way the user could, for example, easily disconnect every single link once #104 lands.

Unfortunately, the path forward is not so clear, since Links are not exposed by Object but rather by the generated skeleton itself. The obvious way is to refactor the way the generated skeleton manages links such that it stores them all in a HashMap for example, but then it feels kind of weird to expose Program and Map iterators through Object but the Link iterator through the skeleton. Any thoughts would be appreciated :)

**Comment by anakryiko** [comment]
Links are way more dynamic objects that are created (potentially multiple times) by user code, not just skeleton. So it's entirely different class. I don't see any other way than either for user to keep track of its own links with custom code or iterating all links system-wide and seeing which links are against programs that belong to application's object.

**Comment by willfindlay** [comment]
> Links are way more dynamic objects that are created (potentially multiple times) by user code, not just skeleton. So it's entirely different class. I don't see any other way than either for user to keep track of its own links with custom code or iterating all links system-wide and seeing which links are against programs that belong to application's object.

Makes sense, thanks for the explanation.

Seems like links were added the libbpf-rs skeleton in 4c7b26023d2ae2f1e4c94e779329cf566bd937cb with the idea being that it makes the user's life easier to manage links generated by `skel.attach()`. Seems like this isn't the most idiomatic approach to begin with, based on what you're saying here...

That being said, since we _are_ storing these links anyway, I don't see a reason why we couldn't at least convert this into a HashMap instead of generating a Struct with a field for every program type.

**Comment by danobi** [comment]
> Seems like this isn't the most idiomatic approach to begin with, based on what you're saying here...

You're right that it's a convenience thing. But I'm not sure I agree with the idiomatic bit. I think it's fine to store `Link`s in the skeleton for user convenience.

However, the inverse is more problematic. It seems difficult, as a framework, to provide a reliable iterator over `Link`s such that the user can disconnect _every_ link. Any such interface like that may be misleading b/c of races and/or missing links. Might be possible to iterate over all system links but not sure how we'd handle races.

You can think of `Program`s as class definitions and `Link`s as instances of the class. It makes sense to have an iterator over `Program`s b/c there's a known number. But we cannot really provide an iterator over `Link`s b/c there's an unknown number.

> That being said, since we are storing these links anyway, I don't see a reason why we couldn't at least convert this into a HashMap instead of generating a Struct with a field for every program.

This seems reasonable to me as a convenience thing. The alternative is the user specifically names each link and disconnects it.

**Comment by willfindlay** [comment]
> However, the inverse is more problematic. It seems difficult, as a framework, to provide a reliable iterator over `Link`s such that the user can disconnect _every_ link. Any such interface like that may be misleading b/c of races and/or missing links. Might be possible to iterate over all system links but not sure how we'd handle races.

Right. I suppose I'll have to bite the bullet and just handle things manually in my project.

> > That being said, since we are storing these links anyway, I don't see a reason why we couldn't at least convert this into a HashMap instead of generating a Struct with a field for every program.
> 
> This seems reasonable to me as a convenience thing. The alternative is the user specifically names each link and disconnects it.

Sure. I'll make a PR at some point. For now, I'll close this.
