### ISSUE TITLE
Development Enviroment

### ISSUE THREAD

**Issue by DevasiaThomas** [libbpf/libbpf-rs#123]
I'm sorry if this is not the right place to ask this, but my question revolves around me trying to tweak certain things in the runqslower example within this repo as part of my foray into ebpfs.

I was able to clone this repo, build and successfully run runqslower. However, when I opened this up in an IDE (I use CLion) ,code navigations into the bpf helper functions in C code didn't work as it didn't know where to find it due to the fact that it cannot find the bpf_helpers header file and suggests me to make a CMake file. 

I believe libbpf-rs itself gets them from libbpf_sys which packs libbpf. Any ideas on how I can point IDE resolution towards this libbpf?

**Comment by danobi** [comment]
Maybe try installing libbpf-dev package? Not sure if clion is smart enough to find system headers

**Comment by DevasiaThomas** [comment]
@danobi Thanks for the quick reply and suggestion, I already had that package installed. It didn't work for me then. But this morning I tried opening the linux source in CLion (they have a [guide](https://docs.google.com/document/d/1--WGVMf4aR2BLQ7DHtqmLVbjICQgos3Qua7-Py9vIo4/edit)) as a different project, so that I could do some partially-manual code searches, and after an hour or so something clicked and the C code within this rust project started taking me to the system headers.
However Rust to C navigation doesn't exist and is being tracked [here](https://github.com/intellij-rust/intellij-rust/issues/6639) 
So some progress :)

I'm closing this, hopefully someone finds this useful

**Comment by thesw4rm** [comment]
My environment is neovim/vim, but I think this can apply to CLion or other editors. I basically created a .ccls file in my project that links to the bpf userspace library. I then compiled the Linux kernel source into a compile_commands.json and made a symbolic link to the root of my project. CCLS will basically build an index of all these things for me and search them whenever I open a C related file (doesn't work for Rust to C as you said). 

In CLion, this should be possible by doing the same steps with CMake. Link the compile_commands.json (absolute paths) to CMake and link the bpf userspace library to your target executable. Link any other headers you need, and after a while CLion should have indexed everything.
