### ISSUE TITLE
bool in bpf code becomes u8 in generated skeleton code

### ISSUE THREAD

**Issue by DevasiaThomas** [libbpf/libbpf-rs#129]
Hi,

The current skel generation does this. I was looking up how to convert the bool properly to u8 when I found [this](https://stackoverflow.com/a/47705543/2277013) . Any thoughts on why the skel generation represents bool in C as u8 in Rust? Also, how would you convert rust bool to rust u8 so that the bool value does get passed to bpf code?

Thanks in advance

**Comment by DevasiaThomas** [comment]
I got this right now
```
fn bool_2_u8(value: bool) -> u8 {
    if value {1} else {0}
}
```
or is something that uses transmute, like [this](https://stackoverflow.com/q/36924530/2277013), be used?

**Comment by danobi** [comment]
Thanks for the report! This is a bug with libbpf-cargo. See the attached PR for the fix.

**Comment by DevasiaThomas** [comment]
Thanks @danobi  :)
