### ISSUE TITLE
do you plan to support percpu based map accessing from the libbpf-rs's map functionalities?

### ISSUE THREAD

**Issue by AlexZhao** [libbpf/libbpf-rs#132]

**Comment by danobi** [comment]
Yeah, we do. I'll pick up #113 this week if there's no further activity

**Comment by AlexZhao** [comment]
> 
> 
> Yeah, we do. I'll pick up #113 this week if there's no further activity

I try to write one for this percpu access functionalities, if need, I can provide this codes which based on your normal lookup functionalities.

**Comment by danobi** [comment]
That'd be great if you could contribute the percpu code (If I'm understanding correctly)

**Comment by AlexZhao** [comment]
> That'd be great if you could contribute the percpu code (If I'm understanding correctly)

BTW, Do you accept new developer for this sw project? if still need helper on developing this libbpf-rs, I can also help to join this.

**Comment by anakryiko** [comment]
Yes, of course, all the contributors are welcome. There is just a limited amount of time in a day and week to do all the code reviews, so sometimes it take long to review the code. But also see https://github.com/libbpf/libbpf-rs/pull/113 as this work is already underway.
