### ISSUE TITLE
Getting code to run cross OS(host) through containers

### ISSUE THREAD

**Issue by DevasiaThomas** [libbpf/libbpf-rs#139]
I have got it working , but I think only partially. @danobi I would like your thoughts on this.

My host is Ubuntu, so is container. But apparently the container comes with BTF info, even though it actually doesn't contain a kernel? I am mounting, right now, just ``sys/kernel/debug`` for the ``capable`` example. And its working, but its probably using the btf from within the container and I'm getting lucky.  Should I be trying to mount the ``sys/kernel/btf`` directory as well?

**Comment by mimullin-bbry** [comment]
Hi @DevasiaThomas Which ubuntu are you running?

If you are running 21.04 or beyond (I haven't tested against 21.10, but I assume they didn't regress this), then yes, you will need to mount /sys/kernel/btf to utilize btf relocations.

the Capable example does not require any btf relocations (eg it isn't doing any BPF_CORE_READ stuff).  But as you start playing, btf relocations will become a need for you.

If you are running on Ubuntu 20.04, the BTF problem is significant, as the kernels in 20.04 do not have btf generation enabled.  There are less-than-optimal ways around this (see: https://github.com/rafaeldtinoco/portablebpf).

**Comment by DevasiaThomas** [comment]
> Hi @DevasiaThomas Which ubuntu are you running?

My host is 21.10 and my container was 21.04.

> If you are running 21.04 or beyond (I haven't tested against 21.10, but I assume they didn't regress this), then yes, you will need to mount /sys/kernel/btf to utilize btf relocations.

Yes, my concern was mainly around if I decided to run the Ubuntu container on a modern RHEL OS as is, I would run into problems with the wrong BTFs. 

> the Capable example does not require any btf relocations (eg it isn't doing any BPF_CORE_READ stuff). But as you start playing, btf relocations will become a need for you.

Lol, I should have looked at what I wrote in capable first! I thought I was using the task struct field for ``comm_str`` for which I would have done a CORE read. Thanks for pointing it out :) .  But yes, my question was in line with me actually using CORE stuff.

> If you are running on Ubuntu 20.04, the BTF problem is significant, as the kernels in 20.04 do not have btf generation enabled. There are less-than-optimal ways around this (see: https://github.com/rafaeldtinoco/portablebpf).

I would love to avoid non CORE stuff, but if I do come across a case, where I cannot use it - I will definitely look this up. thanks for the share

**Comment by DevasiaThomas** [comment]
@mimullin-bbry I came across the below in [tracee](https://github.com/aquasecurity/tracee#quickstart)

>Note: Running with BTF requires access to the kernel configuration file. Depending on the linux distribution it can be in either /proc/config.gz (which docker mounts by default) or /boot/config-$(uname -r) (which must be mounted explicitly).

Their instructions don't talk about mounting the BTF directory that I asked about. Any insights?

**Comment by mimullin-bbry** [comment]
@DevasiaThomas Interesting.  config.gz and /boot/config-$(uname -r) are methods of determining if the kernel was compiled with BTF info.  Neither of these files will include the BTF info, but rather will allow you to grep for CONFIG_DEBUG_INFO_BTF.

The two files are the .config you get out of configuring a kernel, they aren't the BTF info files.

Upon grepping, if you see
CONFIG_DEBUG_INFO_BTF=y
then the kernel is capable of doing bpf (IE It has a /sys/kernel/btf/vmlinux file).

That said, I see nowhere in their example where they mount the /sys/kernel/btf volume.  I wonder if they get all of /sys for free because of --privileged or if there is some more nuance to BTF that I don't fully understand.

If you dive deeper into this rabbit hole, please let me know.  Im quite intregued, but dont have the time to dedicate to understand just how tracee is doing the btf stuff without a /sys/kernel/btf/vmlinux file.

**Comment by DevasiaThomas** [comment]
@mimullin-bbry Yup! I will let you know. The ``--privileged`` only adds all the capabilities available on the system. Else I wouldn't have to mount the /sys/kernel/debug folder. 

Also does the kernel have to be compiled with ``CONFIG_DEBUG_INFO_BTF=y``? or do you just have to provide BTF info for that kernel? what I mean is if I had a target host OS that was never compiled with that option, but I compiled the BTF info for the same kernel-os combo on another host, loaded that BTF into a container -- would that BTF work?

**Comment by mimullin-bbry** [comment]
> Also does the kernel have to be compiled with CONFIG_DEBUG_INFO_BTF=y? or do you just have to provide BTF info for that kernel? 

You just have to provide the BTF info

> I compiled the BTF info for the same kernel-os combo on another host, loaded that BTF into a container -- would that BTF work?

Yes.  I have personally done this for Ubuntu 20.04 kernel version 5.8 aws, gcp, oem and hwe.  I have however failed on PhotonOS.

**Comment by DevasiaThomas** [comment]
Thanks this is good to know.

**Comment by anakryiko** [comment]
The simplest way to check if kernel provides BTF is to check the existence of /sys/kernel/btf/vmlinux. It should be always there if sysfs is mounted. I don't know what are the implications w.r.t. containers.

Libbpf (and thus probably libbpf-rs) provides a way to specify custom kernel BTF through a file if kernel doesn't have its own. Search for BTFHub and BTFGen discussion upstream. This is mostly to be able to run BPF CO-RE apps on old kernels without BTF. It's quite challenging logistically, though, so if you can upgrade to recent enough kernels, that's the best way to do this.

Sorry if I haven't addressed all the questions. Please summarize again with specific questions. Thanks!

**Comment by mimullin-bbry** [comment]
@DevasiaThomas feel free to email me at masmullin at gmail dot com if you ever want to talk BPF :)
