### ISSUE TITLE
[libbpf-cargo] Add support for floats

### ISSUE THREAD

**Issue by insearchoflosttime** [libbpf/libbpf-rs#172]
Floating types were added to libbpf but have not yet been updated in libbpf-cargo

**Comment by kckeiks** [comment]
Hi,
I'm looking to contribute to this project. I have some bandwidth in the next few weeks so I could take a crack at this problem if I can get some guidance on the tasks that need to get done? Seems like we would need to update `BtfType` and some methods in `btf.rs` to handle `BtfType::FLoat`. Let me know if it's ok to pick this work up.

**Comment by insearchoflosttime** [comment]
Hi @kckeiks!! I'm so sorry, I didn't get a notification about your message so I completely missed this. I'd love for you to contribute to this project. It looks like Hengqi just picked up this issue regarding adding support for floats, but I can file a lot more tasks to work on, if you're still interested. 

One of our biggest endeavors this half is for libbpf-rs to reach feature parity with libbpf 1.0. I'll create some tasks tomorrow morning for this milestone, and then we can sync up about which task(s) most interest you (and if none of them do, we can also find something else for you to work on!). Does this sound okay?

**Comment by kckeiks** [comment]
@insearchoflosttime yeah, that sounds great! Thanks for following up!
