### ISSUE TITLE
Statically link BPF object files to avoid having DWARF info

### ISSUE THREAD

**Issue by jyn514** [libbpf/libbpf-rs#177]
As a summary of the conversation in https://github.com/libbpf/libbpf-rs/pull/169, the approach we're going to go with is statically linking BPF object files, which will strip out DWARF info as a side-effect

_Originally posted by @insearchoflosttime in https://github.com/libbpf/libbpf-rs/issues/163#issuecomment-1006820411_

**Comment by javierhonduco** [comment]
This would be amazing. I am currently not checking in the generated skeleton in git due to this
