### ISSUE TITLE
libbpf-rs: Add support for creating map standalone

### ISSUE THREAD

**Issue by zyy17** [libbpf/libbpf-rs#191]
## User Story

We need to create pinned map when some conditions meet, but libbpf-rs only support create map from ELF file.

## Example

libbpf support `bpf_map_create()` and I think we can create the new abstraction to support creating map standalone. Refer to [cilium/ebpf](https://github.com/cilium/ebpf) implementation, maybe we can provide the following API(same as [map.go](https://github.com/cilium/ebpf/blob/master/map.go) but just the demonstration):

```rust
pub struct Map {
    name: String,
    fd: i32,
    typ: libbpf_sys::bpf_map_type,
    key_size: u32,
    value_size: u32,
    max_entries: u32,
    flags: u32,
    pinned_path: String,
}

pub struct MapSpec {
    name: String,
    key_size: u32,
    value_size: u32,
    max_entries: u32,
    map_type: libbpf_sys::bpf_map_type,
    flags: u32,
    pinning: PinType,
}

impl Map {
    pub fn new_map_with_options(spec: MapSpec, opts: MapOptions) -> Result<Self> {  
        /* use create_map() of MapSpec */ 
    }
}

impl MapSpec {
    fn create_map(&self) -> Result<Map> {  /* use libbpf_sys::bpf_map_create() */ }
}
```

After map creating, user space could use `fd` to access map.

**Comment by danobi** [comment]
Can you elaborate what your use case is? And why creating maps from elf file is insufficient?

**Comment by zyy17** [comment]
In my scenario, we use the pinned map like the global configuration that shares between multiple BPF progs. 
For example:
1. Our daemon service will create pinned map after launching;
2. daemon service will accept the RPC request to decide which BPF prog should be loaded and what configuration should be set in the configuration pinned map; 
3. daemon can load multiple BPF progs and control their behavior by the global configuration map;

If we use ELF file(as we currently do), the daemon should always maintain some kind of ELF object file(or can hardcode in the code). I think it's not an elegant way to handle such situations, maybe the standalone API will be the better solution.

**Comment by insearchoflosttime** [comment]
Hi @zyy17, this is definitely on the libbpf-rs roadmap as part of our larger goal to reach feature parity with libbpf 1.0. We will prioritize this. Thanks for your patience.

**Comment by zyy17** [comment]
@insearchoflosttime Looking forward to 1.0 😊  If you agree the design of  map API of cilium/ebpf, maybe I can provide the PR(I already implement the internal version).

**Comment by insearchoflosttime** [comment]
Awesome!! Feel free to submit a PR, @zyy17! We welcome all contributions 😊

libbpf-rs has an existing interface for representing maps (https://github.com/libbpf/libbpf-rs/blob/master/libbpf-rs/src/map.rs#L91), so I don't think we need to create a new "MapSpec" abstraction. I think we could just add a new wrapper function inside the `impl Map { ...` that invokes libbpf_sys::bpf_map_create()

**Comment by zyy17** [comment]
@insearchoflosttime Sounds reasonable to me. I will give it a try and thank you for your help.

**Comment by insearchoflosttime** [comment]
Hi @zyy17 , are you still working on this?

**Comment by zyy17** [comment]
> Hi @zyy17 , are you still working on this?

Sorry for the late response, I miss the github message... As the above notice, I already submit my PR and look forward to your comments :)
