### ISSUE TITLE
libbpf: prog 'bpf_sockops': failed to attach to cgroup: Bad file descriptor

### ISSUE THREAD

**Issue by yefy** [libbpf/libbpf-rs#197]
# question
```
how attach sk_msg and socksops
```

# Description
```
Ubuntu 21.04
kernel-5.9.11
clang-11
llvm-11
rust-1.56.1-x86_64-unknown-linux-gnu (default)
```

# error example
```
https://github.com/yefy/ebpf-sockhash-rs
```

# error codes from  https://github.com/yefy/ebpf-sockhash-rs
```
SEC("sk_msg")
int bpf_sk_msg_verdict(struct sk_msg_md *msg)
{
    return SK_PASS;
}

SEC("sockops")
int bpf_sockops(struct bpf_sock_ops *skops)
{
    return 0;
}


let sock_hash_fd = skel.maps_mut().sock_hash().fd();
    let _bpf_sk_msg_verdict = skel
        .progs_mut()
        .bpf_sk_msg_verdict()
        .attach_sockmap(sock_hash_fd)?;

let cgroup_fd = std::fs::OpenOptions::new()
        //.custom_flags(libc::O_DIRECTORY)
        //.create(true)
        .read(true)
        .write(false)
        .open("/sys/fs/cgroup/unified/")
        .map_err(|e| anyhow::anyhow!("open e:{}", e))?
        .as_raw_fd();
    let _bpf_sockops = skel
        .progs_mut()
        .bpf_sockops()
        .attach_cgroup(cgroup_fd)?;
```

**Comment by chenhengqi** [comment]
I think this problem is not related to libbpf-rs.

Do you have `/sys/fs/cgroup/cgroup.controllers` in your system ?

**Comment by chenhengqi** [comment]
OK, now I see why you got the error.

```rust
let cgroup_fd = std::fs::OpenOptions::new()
        //.custom_flags(libc::O_DIRECTORY)
        //.create(true)
        .read(true)
        .write(false)
        .open("/sys/fs/cgroup/unified/")
        .map_err(|e| anyhow::anyhow!("open e:{}", e))?
        .as_raw_fd();
// File::drop here
```

You have to do:
```rust
let f = std::fs::OpenOptions::new()
        //.custom_flags(libc::O_DIRECTORY)
        //.create(true)
        .read(true)
        .write(false)
        .open("/sys/fs/cgroup/unified/")?;
let cgroup_fd =  f.as_raw_fd();
```

:)

**Comment by yefy** [comment]
> OK, now I see why you got the error.
> 
> ```rust
> let cgroup_fd = std::fs::OpenOptions::new()
>         //.custom_flags(libc::O_DIRECTORY)
>         //.create(true)
>         .read(true)
>         .write(false)
>         .open("/sys/fs/cgroup/unified/")
>         .map_err(|e| anyhow::anyhow!("open e:{}", e))?
>         .as_raw_fd();
> // File::drop here
> ```
> 
> You have to do:
> 
> ```rust
> let f = std::fs::OpenOptions::new()
>         //.custom_flags(libc::O_DIRECTORY)
>         //.create(true)
>         .read(true)
>         .write(false)
>         .open("/sys/fs/cgroup/unified/")?;
> let cgroup_fd =  f.as_raw_fd();
> ```
> 
> :)

```
that's right. thanks for helping me
```

**Comment by insearchoflosttime** [comment]
Closing this issue. Thanks @chenhengqi for helping!
