### ISSUE TITLE
Get/set bpf program flags

### ISSUE THREAD

**Issue by insearchoflosttime** [libbpf/libbpf-rs#198]
Implement the ability to get and set program flags. This should be a wrapper around the libbpf library's

`__u32 bpf_program__flags(const struct bpf_program *prog);`

and

`int bpf_program__set_flags(struct bpf_program *prog, __u32 flags);`

(https://github.com/libbpf/libbpf/blob/master/src/libbpf.c#L8538-L8550). 

The libbpf-rs code for interacting with programs is located at libbpf-rs/src/program.rs

**Comment by insearchoflosttime** [comment]
@kckeiks, would this be something you're interested in?

**Comment by kckeiks** [comment]
Yeah I can this one and #200
