### ISSUE TITLE
Add bpf link functionality

### ISSUE THREAD

**Issue by insearchoflosttime** [libbpf/libbpf-rs#199]
As part of our effort to reach feature parity with libbpf-1.0, add a libbpf-rs interface for interacting with bpf links:

LIBBPF_API struct bpf_link *bpf_link__open(const char *path);
LIBBPF_API const char *bpf_link__pin_path(const struct bpf_link *link);
LIBBPF_API void bpf_link__disconnect(struct bpf_link *link);
LIBBPF_API int bpf_link__detach(struct bpf_link *link);

(https://github.com/libbpf/libbpf/blob/3591deb9bc6b0848721f831790b78ae0a593b4c5/src/libbpf.h#L378-L387)

**Comment by kckeiks** [comment]
FYI `bpf_link__disconnect` was already added.
