### ISSUE TITLE
Support bpf_xdp_attach and bpf_xdp_detach

### ISSUE THREAD

**Issue by insearchoflosttime** [libbpf/libbpf-rs#205]
Defined in libbpf as:
```
LIBBPF_API int bpf_xdp_attach(int ifindex, int prog_fd, __u32 flags,
			      const struct bpf_xdp_attach_opts *opts);
LIBBPF_API int bpf_xdp_detach(int ifindex, __u32 flags,
			      const struct bpf_xdp_attach_opts *opts);
```
https://github.com/libbpf/libbpf/blob/3591deb9bc6b0848721f831790b78ae0a593b4c5/src/libbpf.h#L898-L901

**Comment by Noah-Kennedy** [comment]
Is this blocked on anything? If not, I'd be willing to contribute this.

**Comment by danielocfb** [comment]
> Is this blocked on anything? If not, I'd be willing to contribute this.

I am not aware of any blockers. Please, feel free to go ahead and open a pull request @Noah-Kennedy.

**Comment by danielocfb** [comment]
Fixed by https://github.com/libbpf/libbpf-rs/pull/625
