### ISSUE TITLE
Support traversing an object's programs (bpf_object__next_program and bpf_object__prev_program)

### ISSUE THREAD

**Issue by insearchoflosttime** [libbpf/libbpf-rs#208]
Libbpf has these APIs
```
LIBBPF_API struct bpf_program *
bpf_object__next_program(const struct bpf_object *obj, struct bpf_program *prog);

LIBBPF_API struct bpf_program *
bpf_object__prev_program(const struct bpf_object *obj, struct bpf_program *prog);
```
that libbpf-rs should have wrappers around for userspace applications to use

https://github.com/libbpf/libbpf/blob/3591deb9bc6b0848721f831790b78ae0a593b4c5/src/libbpf.h#L269-L280

**Comment by anakryiko** [comment]
don't we have program and map iterators? C doesn't have a concept of iterators, but Rust does. I don't think we need to expose bpf_object__{next,prev}_{program,map}() as is

**Comment by insearchoflosttime** [comment]
Nice, it looks like we do (https://github.com/libbpf/libbpf-rs/blob/master/libbpf-rs/src/object.rs#L252). I'll mark this as closed
