### ISSUE TITLE
Support updating bpf links

### ISSUE THREAD

**Issue by insearchoflosttime** [libbpf/libbpf-rs#210]
To update a link in libbpf, there is this API:

```
LIBBPF_API int bpf_link_update(int link_fd, int new_prog_fd,
			       const struct bpf_link_update_opts *opts);
```
https://github.com/libbpf/libbpf/blob/3591deb9bc6b0848721f831790b78ae0a593b4c5/src/bpf.h#L434

In libbpf-rs, we should support this operation as well

**Comment by danielocfb** [comment]
Let's add this once a use case has been identified.
