### ISSUE TITLE
the use of btf_custom_path

### ISSUE THREAD

**Issue by dafu-wu** [libbpf/libbpf-rs#231]
I'm new to Rust，How do I pass the BTF file to btf_custom_path？
thank you very much for taking the time to answer my little friend.

**Comment by insearchoflosttime** [comment]
Hi @dafu-wu. Can you clarify your use case? We don't currently support passing in a BTF file.

**Comment by dafu-wu** [comment]
> 

First of all, thank you. Some of the kernel CONFIG_DEBUG_INFO_BTF=n,but we can get BTF file from btfhub or pahole,so,I want to pass a local BTF file to 'bpf_object__open_file'.

**Comment by insearchoflosttime** [comment]
Gotcha, I just took a look at https://lpc.events/event/11/contributions/948/attachments/906/1776/LPC21_Towards_truly_portable_eBPF.pdf which has some more information about btfhub and using a custom external BTF file.

If you want to pass in the BTF file to btf_custom_path on your local version of libbpf-rs, I think you'll need to expand ObjectBuilder::opts to take in a the btf custom path as an arg, and then pass that to the libpf_sys::bpf_object_open_opts call (https://github.com/libbpf/libbpf-rs/blob/master/libbpf-rs/src/object.rs#L50). Does this answer your question?

**Comment by chengshuyi** [comment]
'''
pub fn open(mut self) -> libbpf_rs::Result<OpenIcmpSkel<'a>> {
        let mut skel_config = build_skel_config()?;
        let open_opts = self.obj_builder.opts(std::ptr::null());

        let ret = unsafe { libbpf_sys::bpf_object__open_skeleton(skel_config.get(), &open_opts) };
        if ret != 0 {
            return Err(libbpf_rs::Error::System(-ret));
        }

        let obj = unsafe { libbpf_rs::OpenObject::from_ptr(skel_config.object_ptr())? };

        Ok(OpenIcmpSkel { obj, skel_config })
    }
'''

Maybe we can refer to the code generated by libbpf-cargo and add an open_opts function. 

'''
 pub fn open_opts(mut self, open_opts: libbpf_sys::bpf_object_open_opts) -> libbpf_rs::Result<OpenIcmpSkel<'a>> {
        let mut skel_config = build_skel_config()?;
        // let open_opts = self.obj_builder.opts(std::ptr::null());

        let ret = unsafe { libbpf_sys::bpf_object__open_skeleton(skel_config.get(), &open_opts) };
        if ret != 0 {
            return Err(libbpf_rs::Error::System(-ret));
        }

        let obj = unsafe { libbpf_rs::OpenObject::from_ptr(skel_config.object_ptr())? };

        Ok(OpenIcmpSkel { obj, skel_config })
    }
'''

**Comment by dafu-wu** [comment]
> ```
> pub fn open(mut self) -> libbpf_rs::Result<OpenIcmpSkel<'a>> {
>         let mut skel_config = build_skel_config()?;
>         let open_opts = self.obj_builder.opts(std::ptr::null());
> 
>         let ret = unsafe { libbpf_sys::bpf_object__open_skeleton(skel_config.get(), &open_opts) };
>         if ret != 0 {
>             return Err(libbpf_rs::Error::System(-ret));
>         }
> 
>         let obj = unsafe { libbpf_rs::OpenObject::from_ptr(skel_config.object_ptr())? };
> 
>         Ok(OpenIcmpSkel { obj, skel_config })
>     }
> ```
> 
> Maybe we can refer to the code generated by libbpf-cargo and add an open_opts function.
> 
> ```
>  pub fn open_opts(mut self, open_opts: libbpf_sys::bpf_object_open_opts) -> libbpf_rs::Result<OpenIcmpSkel<'a>> {
>         let mut skel_config = build_skel_config()?;
>         // let open_opts = self.obj_builder.opts(std::ptr::null());
> 
>         let ret = unsafe { libbpf_sys::bpf_object__open_skeleton(skel_config.get(), &open_opts) };
>         if ret != 0 {
>             return Err(libbpf_rs::Error::System(-ret));
>         }
> 
>         let obj = unsafe { libbpf_rs::OpenObject::from_ptr(skel_config.object_ptr())? };
> 
>         Ok(OpenIcmpSkel { obj, skel_config })
>     }
> ```

@chengshuyi  thanks a lot,I think this is a very good solution,do you plan to propose a PR for libbpf-rs ？If not, I plan to submit one after sorting.

**Comment by dafu-wu** [comment]
> Gotcha, I just took a look at https://lpc.events/event/11/contributions/948/attachments/906/1776/LPC21_Towards_truly_portable_eBPF.pdf which has some more information about btfhub and using a custom external BTF file.
> 
> If you want to pass in the BTF file to btf_custom_path on your local version of libbpf-rs, I think you'll need to expand ObjectBuilder::opts to take in a the btf custom path as an arg, and then pass that to the libpf_sys::bpf_object_open_opts call (https://github.com/libbpf/libbpf-rs/blob/master/libbpf-rs/src/object.rs#L50). Does this answer your question?

Thank you very much for your help，there seems to be no corresponding method to deliver  btf_custom_path. I think the method of @chengshuyi  may be a good way.

**Comment by chengshuyi** [comment]
> 



> > ```
> > pub fn open(mut self) -> libbpf_rs::Result<OpenIcmpSkel<'a>> {
> >         let mut skel_config = build_skel_config()?;
> >         let open_opts = self.obj_builder.opts(std::ptr::null());
> > 
> >         let ret = unsafe { libbpf_sys::bpf_object__open_skeleton(skel_config.get(), &open_opts) };
> >         if ret != 0 {
> >             return Err(libbpf_rs::Error::System(-ret));
> >         }
> > 
> >         let obj = unsafe { libbpf_rs::OpenObject::from_ptr(skel_config.object_ptr())? };
> > 
> >         Ok(OpenIcmpSkel { obj, skel_config })
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Maybe we can refer to the code generated by libbpf-cargo and add an open_opts function.
> > ```
> >  pub fn open_opts(mut self, open_opts: libbpf_sys::bpf_object_open_opts) -> libbpf_rs::Result<OpenIcmpSkel<'a>> {
> >         let mut skel_config = build_skel_config()?;
> >         // let open_opts = self.obj_builder.opts(std::ptr::null());
> > 
> >         let ret = unsafe { libbpf_sys::bpf_object__open_skeleton(skel_config.get(), &open_opts) };
> >         if ret != 0 {
> >             return Err(libbpf_rs::Error::System(-ret));
> >         }
> > 
> >         let obj = unsafe { libbpf_rs::OpenObject::from_ptr(skel_config.object_ptr())? };
> > 
> >         Ok(OpenIcmpSkel { obj, skel_config })
> >     }
> > ```
> 
> @chengshuyi thanks a lot,I think this is a very good solution,do you plan to propose a PR for libbpf-rs ？If not, I plan to submit one after sorting.

ok, i'm glad to submit a pr. I will finish it this week.

**Comment by dafu-wu** [comment]
#232

**Comment by dafu-wu** [comment]
@chengshuyi 

` let mut btf_custom_path_fd: *const i8 = std::ptr::null();

    let btf_custom_path = "/test/vmlinux.btf";
    let _path = CString::new(btf_custom_path).unwrap();
    btf_custom_path_fd = _path.as_ptr();
    println!("btf_custom_path_fd:{:#?}", btf_custom_path_fd);

    let mut open_skel_conn4_builder = Connect4SkelBuilder::default();
    let mut conn4_opts = open_skel_conn4_builder.obj_builder.opts(std::ptr::null());
    conn4_opts.btf_custom_path = btf_custom_path_fd;
    let mut open_skel_conn4 = open_skel_conn4_builder.open_opts(conn4_opts)?;`
    
  
 happen errs:
`libbpf: failed to parse target BTF: -2
libbpf: failed to perform CO-RE relocations: -2
libbpf: failed to load object 'connect4_bpf'
libbpf: failed to load BPF skeleton 'connect4_bpf': -2
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: System(2)'`

Please advise the， Am I using it the wrong way？

**Comment by chengshuyi** [comment]
> 

Do you use other higher kernel features which would load btf into kernel? btf_custom_path is not valid in this scene.

**Comment by dafu-wu** [comment]
> 

maybe,i pass btf_custom_path err，How did you do it？

**Comment by dafu-wu** [comment]
> Hello, I guess you are not intended to ping me.
> 
> You can use bpftool to validate your BTF file.
> 
> ```shell
> $ bpftool btf dump file your.btf
> ```

thank you for your help!👍
