### ISSUE TITLE
Add support for bpf_program__attach_uprobe_opts

### ISSUE THREAD

**Issue by insearchoflosttime** [libbpf/libbpf-rs#235]
bpf_program__attach_uprobe_opts in libbpf: https://github.com/libbpf/libbpf/blob/master/src/libbpf.h#L603-L604

**Comment by danielocfb** [comment]
I think this feature's implementation can be similar to what we do [here](https://github.com/libbpf/libbpf-rs/pull/309), so I'll wait until we have agreement on the approach proposed there and then use the same one.
