### ISSUE TITLE
What happens to a uprobe when the .so file it linked to gets deleted?

### ISSUE THREAD

**Issue by thesw4rm** [libbpf/libbpf-rs#238]
Hi,

I created a uprobe and attached it to libssl within an actively running container (accessed the container's filesystem using the root process' directory in procfs). The uprobe is intercepting function calls as expected and reporting results. When I kill and delete the container, the uprobe will obviously not report any events any more, but I was wondering what happens to it? 

Is there a clean-up process somewhere in the kernel that removes the uprobe's hooks, or does it just become a dangling pointer? If uprobe is a dangling pointer, are we able to clean it up from the userspace loader?

**Comment by insearchoflosttime** [comment]
If I am understanding your question correctly, your question is the same as [this one](https://github.com/iovisor/bcc/issues/2640) (and please correct me if it's not :)). Copy & pasting from that thread:

"In your case the uprobe is attached to the file (inode). As long as the inode does not change, all future processes mapping the file will have the uprobe.
You may read https://www.kernel.org/doc/Documentation/trace/uprobetracer.txt . BPF is on top of the generic uprobe.

If the target process exits, you still need to clean up, especially if you are using global uprobe not tied to the process.

If BCC exists abnormally like it crashed, if you are using the debugfs-file-based uprobe, then yes, the uprobe will still exist from the system's perspective and would still take effect on the attached binary. If you are using Perf Event-based uprobe, then even if BCC crashes it should be cleaned by by the Kernel, and that is exactly one of the reason we prefer Perf Event based probes."

Does this answer your question?

**Comment by thesw4rm** [comment]
That's a great find thank you! Not sure why I didn't find it while researching. 

I think the libbpf functions I am calling are using a file based uprobe to attach to a shared library, because there isn't really another method that would make sense.

The person who answered says that if the target process exits, then even an attached global uprobe needs to be cleaned up. Why would a global/file-based uprobe dangle if a process exits? Is there a separate clone created for each process? In that case, is the uprobe not instantiated until a process is created that loads the file the uprobe is watching? So even if the file gets deleted and there aren't any processes that were/are using it, the uprobe doesn't dangle assuming it was cleaned up properly so far?

>  If you are using Perf Event-based uprobe, then even if BCC crashes it should be cleaned by by the Kernel, and that is exactly one of the reason we prefer Perf Event based probes

I'm guessing libbpf uprobes are perf-event based by default? So effectively this is like saying BCC uprobes would survive process crash and libbpf ones would not?

**Comment by anakryiko** [comment]
@insearchoflosttime, @thesw4rm this discussion should be happening on the mailing list so more people from bpf community can read this, learn from and/or contribute to the discussion. This is not libbpf-rs specific.

**Comment by thesw4rm** [comment]
@anakryiko fair point! I asked twice on the mailing list. The question you quoted on there was posted by me. It didn't get any traction. I wanted to get an answer here and cross post it there for others.

**Comment by insearchoflosttime** [comment]
Closing per discussion moving to https://lore.kernel.org/bpf/OBzRUbPFxraCqyqKJG4wxt16KtWfSZuzR1_huzK30nTPOyc2_oKjBYylXc9fr0CL_oOi0SbH8P67jujAXcI8rMT_wZQwfcAblzuteWLv5fg=@pm.me/T/
