### ISSUE TITLE
Is there any plan to release the new version 0.18.0 in the near future？

### ISSUE THREAD

**Issue by dafu-wu** [libbpf/libbpf-rs#240]
If inscribe.

**Comment by insearchoflosttime** [comment]
Hi @dafu-wu , I can push it out this week.

**Comment by dafu-wu** [comment]
> Hi @dafu-wu , I can push it out this week.

Thank you very much,Look forward to it.

**Comment by insearchoflosttime** [comment]
@dafu-wu, libbpf-rs 0.18.0 was just released.
