### ISSUE TITLE
Link to examples in Docs.rs  is broken 

### ISSUE THREAD

**Issue by brandshaide** [libbpf/libbpf-rs#25]
[Docs.rs for the crate](https://docs.rs/libbpf-rs/0.4.0/libbpf_rs/) is containing a link to examples which is broken (404): 

https://docs.rs/libbpf-rs/0.4.0/libbpf_rs/#example

**Comment by danobi** [comment]
Thanks for reporting. Fixed in 1e85dfebb923541.
