### ISSUE TITLE
Derive Debug

### ISSUE THREAD

**Issue by mdaverde** [libbpf/libbpf-rs#260]
Possible to derive [Debug](https://doc.rust-lang.org/std/fmt/trait.Debug.html) trait output for some of the public-facing structs?

Besides the ability to debug from the output, when we build higher-level structs that use libbpf-rs's types internally, we can't derive `Debug` for our custom structs because we get a compiler error notifying us that libbpf-rs's types themselves don't implement `Debug`. 

It seems like we already do this for [some](https://github.com/libbpf/libbpf-rs/blob/master/libbpf-rs/src/tc.rs#L36) [structs](https://github.com/libbpf/libbpf-rs/blob/master/libbpf-rs/src/tc.rs#L219) but not others.

**Comment by danielocfb** [comment]
Agreed, we most likely should do that.

**Comment by danielocfb** [comment]
@mdaverde Are you interested in creating a pull request adding these derives? Should probably include warning on the `missing_debug_implementations` lint.

**Comment by danielocfb** [comment]
With https://github.com/libbpf/libbpf-rs/pull/266 merged the scope of this issue got reduced to adding a few more `Debug` implementations to `struct`s containing pointers.
