### ISSUE TITLE
ksyscall support

### ISSUE THREAD

**Issue by grubeli** [libbpf/libbpf-rs#264]
According to [Journey to libbpf v1](https://nakryiko.com/posts/libbpf-v1/), there is a better option to trace  syscalls - `ksyscall`.
Is the `ksyscall` supported in this crate?

I was unable to use `SEC("ksyscall/openat")`

**Comment by insearchoflosttime** [comment]
ksyscall is not currently supported in this crate, but we should add this.

**Comment by insearchoflosttime** [comment]
If you try again, I think this is supported now after we updated to libbpf-sys v1.0.0
