### ISSUE TITLE
libbpf-cargo does not honor alignment of struct

### ISSUE THREAD

**Issue by zhaiyan920** [libbpf/libbpf-rs#270]
Hi, I've encountered this when using SkeletonBuilder: if the bpf code has "aligned" attribute on struct, then generated type does not correctly correspond to that.

I created a reproducible here: https://github.com/zhaiyan920/reproducible/tree/main/libbpf-cargo-not-honor-alignment, with libbpf-rs=0.18.0 and libbpf-cargo=0.12.0.

When running the build, it turns out

```
struct TestData {
  int data;
} __attribute__((aligned(16)));

struct TestData data[1];
```
is generated as
```
pub mod test_bss_types {
    #[derive(Debug, Copy, Clone)]
    #[repr(C)]
    pub struct bss {
        pub data: [TestData; 1],
    }
    #[derive(Debug, Default, Copy, Clone)]
    #[repr(C)]
    pub struct TestData {
        pub data: i32,
    }
}
```

BTF entry itself reflects the content correctly
```
[1] PTR '(anon)' type_id=0
[2] FUNC_PROTO '(anon)' ret_type_id=3 vlen=1
        'ctx' type_id=1
[3] INT 'int' size=4 bits_offset=0 nr_bits=32 encoding=SIGNED
[4] FUNC 'prog' type_id=2 linkage=global
[5] STRUCT 'TestData' size=16 vlen=1
        'data' type_id=3 bits_offset=0
[6] ARRAY '(anon)' type_id=5 index_type_id=7 nr_elems=1
[7] INT '__ARRAY_SIZE_TYPE__' size=4 bits_offset=0 nr_bits=32 encoding=(none)
[8] VAR 'data' type_id=6, linkage=global
[9] DATASEC '.bss' size=0 vlen=1
        type_id=8 offset=0 size=16 (VAR 'data')
```

So it seems like an issue in code generation.

**Comment by danielocfb** [comment]
Hi @zhaiyan920 , thanks for the report. We have also hit this issue but haven't gotten around looking into a fix. Do you have the cycles to take this on, by any chance?

**Comment by danielocfb** [comment]
@zhaiyan920 can you check if https://github.com/danielocfb/libbpf-rs/tree/topic/fix-align works for you?

**Comment by zhaiyan920** [comment]
hi @danielocfb, sorry for missing previous message. I just briefly tested with my repo, pointing to your branch didn't address the issue. Here is what it generated 
`
struct TestData {
  int data;
} __attribute__((aligned(16)));
`
becomes
`
    pub mod test_bss_types {
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct bss {
            pub data: [TestData; 1],
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct TestData {
            pub data: i32,
        }
    }
`
I am currently unavailable to work on anything that needs focus. But I may have more time to look at this after new year :)

**Comment by danielocfb** [comment]
Hm...are you sure you tested with an up-to-date `cargo-libbpf` binary? When I run `cargo libbpf build` on your repository, with exactly these C definitions, I end up with after the change:
```rust
pub mod test_bss_types {
    #[derive(Debug, Copy, Clone)]
    #[repr(C)]
    pub struct bss {
        pub data: [TestData; 1],
    }
    #[derive(Debug, Default, Copy, Clone)]
    #[repr(C)]
    pub struct TestData {
        pub data: i32,
        __pad_4: [u8; 12],
    }
}
```
