### ISSUE TITLE
Some improvement suggestion about util.rs

### ISSUE THREAD

**Issue by AlexZhao** [libbpf/libbpf-rs#271]
Hi, all

There is something may need to consider about improving correctness of util parse_ret functionalities.
the original existed functions
pub fn parse_ret(ret: i32) -> Result<()> {
    if ret < 0 {
        // Error code is returned negative, flip to positive to match errno
        Err(Error::System(-ret))
    } else {
        Ok(())
    }
}

direct reverse the return value to positive value, but according to bpf syscall manual
https://man7.org/linux/man-pages/man2/bpf.2.html

the syscall of bpf direct return -1 when error happend, but like all syscall, it set errno to indicate what happened, do you see is it possible to use errno to fill the return Err() instead of reverse failed ret -1, then you can know what really happened when checking the return value?

Br
Alex

**Comment by AlexZhao** [comment]
Seems the release libbpf within FC35 is version 0.7, and is there any possibility to detect it within libbpf-rs to make it can work across a wider range of libbpf version compatibility?

**Comment by danielocfb** [comment]
@AlexZhao Others can correct me if my understanding is wrong, but `libbpf-rs` is expected to bind to a specific range of `libbpf` versions, and that is defined by `libbpf-sys`: https://github.com/libbpf/libbpf-sys#versioning

Specifically, version `0.7*` of `libbpf-sys` is compatible with `libbpf` version `0.7.*`. However, as per the [semantic versioning contract](https://doc.rust-lang.org/cargo/reference/resolver.html#semver-compatibility) that it follows, `1.0` is incompatible with `0.7`. I doubt we want to include some kind of hack to detect and explicitly support working with version `0.7` of `libbpf` in our `0.19` strain of the crate (which uses `libbpf-sys` `1.0+`).

If I am understanding correctly, Fedora rawhide [ships with](https://repology.org/project/libbpf/versions) `libbpf` `1.1.0`, which I believe to translate to Fedora 38 likely shipping with it. So your options seem to be: use an older version of `libbpf-rs`, use the vendored `libbpf` and link statically, or upgrade to Fedora rawhide (or wait until Fedora 38).
