### ISSUE TITLE
fail to bind uprobe program to a go binary program

### ISSUE THREAD

**Issue by Zhongy95** [libbpf/libbpf-rs#272]
As I tried to bind a uprobe program to a simple go-grpc program,I failed.
see https://github.com/pixie-io/pixie-demos/tree/main/http2-tracing ,I tried to bind uprobe program to symbol "(loopyWriter)writerHeader"
The output seems Ok, but as I started client program, there was no bpf_printk output.
my user-space code:
`

    let bi_path = "/tmp/grpc_server";
    let file_path = Path::new(bi_path);

    let symbol = "google.golang.org/grpc/internal/transport.(*loopyWriter).writeHeader";

    let addr = get_symbol_address(bi_path,symbol).unwrap();

    skel.links.loopyWriter = skel
        .progs_mut()
        .loopyWriter()
        .attach_uprobe(false, -1, bi_path, addr).expect("fail to attach").into();
`

and my kernel-space code:
`SEC("uprobe")
int loopyWriter(struct pt_regs* ctx)
{
    int ret =0;

    int pid = bpf_get_current_pid_tgid() >> 32;

    bpf_printk("grpc detected!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! %d",pid);

    return 0;

}`

**Comment by Zhongy95** [comment]
I change my go version from 1.19 to 1.15 and recompile my program,then the uprobe failed to created:

```
libbpf:uprobe perf_event_open() failed: ERROR: strerror_r(-524)=22
libbpf: prog 'loopyWriter': failed to create uprobe '/tmp/grpc_server:0x7517e0' perf event: ERROR: strerror_r(-524)=22
thread 'main' panicked at 'fail to attach: Failed to attach uprobe

Caused by:
    System error, errno: -524', src/main.rs:144:61
note: run with \`RUST_BACKTRACE=1\` environment variable to display a backtrace
```

**Comment by Zhongy95** [comment]
I change my go version from 1.19 to 1.15 and recompile my grpc program.Then the uprobe fail to attach:
```
libbpf: uprobe perf_event_open() failed: ERROR: strerror_r(-524)=22
libbpf: prog 'loopyWriter': failed to create uprobe '/tmp/grpc_server:0x7517e0' perf event: ERROR: strerror_r(-524)=22
thread 'main' panicked at 'fail to attach: Failed to attach uprobe

Caused by:
    System error, errno: -524', src/main.rs:144:61
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by anakryiko** [comment]
it will depend on what "get_symbol_address" actually does. Kernel expects file offset of the function you want to attach to. This isn't necessarily the same as symbol address, so I'd look into that some more.

**Comment by Zhongy95** [comment]
您好，我是钟源，这是一封自动回复邮件，您的邮件我已收到，我会尽快回复您的！！

**Comment by Zhongy95** [comment]
您好，我是钟源，这是一封自动回复邮件，您的邮件我已收到，我会尽快回复您的！！

**Comment by insearchoflosttime** [comment]
Closing this issue. Please reopen if you are still stuck on this
