### ISSUE TITLE
XDP Support Planned?

### ISSUE THREAD

**Issue by kbknapp** [libbpf/libbpf-rs#28]
Is there any plan to support the XDP portions of `libbpf`? If so, are there thoughts on how you would like that accomplished so people can submit PRs or contributions to that end?

Thanks!

**Comment by danobi** [comment]
Have you taken a look at https://crates.io/crates/afxdp yet?

I'm not sure too much XDP stuff belongs in libbpf -- there was some discussion a while ago about how it was a historical mistake (cc @anakryiko).

**Comment by kbknapp** [comment]
I saw that it exists when looking at the `libbpf_sys` crate, but I have not yet tried it out. It may very well meet my use case, I'll look into it here shortly. Totally understand if you want to take this crate into a more opinionated direction, I was just curious what the plans were if any to extend since upstream `libbpf` does contain XDP functionality (even the XDP Project seems to be relying on `libbpf` solely from what I can see). Do you know then, are the XDP sections of `libbpf_sys` (or upstream `libbpf`) going to be deprecated/split off?

**Comment by anakryiko** [comment]
Depends what is XDP functionality. APIs like bpf_program__attach_xdp() is definitely part of libbpf. The xsk.c parts of libbpf are probably going to be moved out of libbpf eventually, as they are not very BPF specific.

**Comment by kbknapp** [comment]
I did some playing with `afxdp`, and the API doesn't quite suit my use case. Not saying it couldn't, but it's not nearly as fleshed out as this crate. It could just be the way I'm trying to use it since I'm still new to BPF, but my mental model works much closer to how this crate is laid out. I'll continue to play with it, and see if I find something that is PRable that doesn't work against that API but still covers my use case.

> Depends what is XDP functionality. APIs like bpf_program__attach_xdp() is definitely part of libbpf.

Yeah, its that level of functionality that I was looking for, nothing super advanced.

**Comment by danobi** [comment]
> Yeah, its that level of functionality that I was looking for, nothing super advanced.

Feel free to send PRs :)
