### ISSUE TITLE
Update to libbpf-sys 1.0.3+v1.0.1

### ISSUE THREAD

**Issue by alexforster** [libbpf/libbpf-rs#280]
See here: https://github.com/libbpf/libbpf-sys/issues/46

**Comment by masmullin2000** [comment]
Now that libbpf-sys has reached 1.0, should libbpf-rs now omit the patch version of libbpf-sys in the cargo.toml?

Such a fix would not be necessary, and no rev new crates.io push would be required if

```
libbpf-sys = "1.0"
```

**Comment by danielocfb** [comment]
> Such a fix would not be necessary, and no rev new crates.io push would be required if
> 
> ```
> libbpf-sys = "1.0"
> ```

Not making any statement about the necessity of a new release in one way or another, but to the best of my knowledge, the claim about omitting a patch version causing the stated change is not true.

From https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-cratesio:
```
1.2.3  :=  >=1.2.3, <2.0.0
1.2    :=  >=1.2.0, <2.0.0
1      :=  >=1.0.0, <2.0.0
```

That is, for the intents and purposes of this discussion (which pertains necessary dependency bumps to higher versions), version specifications `1.0.3` and `1.0` are equivalent -- the acceptable upper version that can be selected by Cargo is the same.

**Comment by masmullin2000** [comment]
Ah, Ok.  Thanks for educating me, now I understand the ^ symbol :)

**Comment by danielocfb** [comment]
We do have `0.19.1` and `0.13.1`, respectively, by now, so this issue should have been addressed.
