### ISSUE TITLE
How can I access `*const bpf_object`, `*const bpf_map` from corresponding Rust structs?

### ISSUE THREAD

**Issue by Officeyutong** [libbpf/libbpf-rs#360]
Like the title. I'm going to get the raw pointer and do some operations manually with `libbpf-sys`, but I didn't find any way to access underlying raw pointer in `Object` or `Map`

**Comment by danielocfb** [comment]
I don't believe we expose that currently. But we probably should, similar to what we did over here https://github.com/libbpf/libbpf-rs/pull/348.

@Officeyutong do you want to work on exposing that?
