### ISSUE TITLE
Request for Patch Version update to crates.io

### ISSUE THREAD

**Issue by mimullin-bbry** [libbpf/libbpf-rs#377]
Rust 1.68 was released as stable this morning.  The clippy lint derivable_impls is now in effect for stable rust.

Requesting a new patch version be created for crates.io including this code to clean up any CI/CD problems the new derivable_impls causes.

https://github.com/libbpf/libbpf-rs/commit/5553d9ce572e56f0dabbbd9268b623f6e067a52a

**Comment by danielocfb** [comment]
I want to get one more thing landed before we cut a new release. But I agree that one is overdue. Can you share a bit more what problems you are blocked on? Are they applicable to others?

**Comment by danielocfb** [comment]
> Request for Patch Version update

I think we have to bump the minor version. There were some breaking changes such as fb1e26730b9f87a8fa977c4c1c5213ea90bc6392 (which claims to change things internally but in reality touches the public API surface from what I can tell).

**Comment by mimullin-bbry** [comment]
> Can you share a bit more what problems you are blocked on?

We're technically not "blocked" by anything.  We use -D "warnings" during git pre-commit and CI/CD.  We have chosen to remain on rust version 1.67.1 until the fix for derivable_impls is integrated.

I've seen the milestone road map you've set out (https://github.com/libbpf/libbpf-rs/milestone/2) and wasn't aware that current code required a minor version bump rather than a patch version bump.

I can understand not wanting to bump the minor version until the milestones are met, and we can add some exclusions to our pipeline when we upgrade to 1.68; as such we aren't blocked.

**Comment by danielocfb** [comment]
Thanks, makes sense. It's not a problem to create a minor version bump, I just wanted to mention it in case you were *expecting* a patch version increase. Yeah, I created the milestone but I was unable to make much progress on some of the items. So at this point I fully expect that a few of them will only be addressed in subsequent releases (which doesn't help but it is what it is).

**Comment by danielocfb** [comment]
Will be done once https://github.com/libbpf/libbpf-rs/pull/384 is merged.

**Comment by danielocfb** [comment]
> Will be done once #384 is merged.

Done.
