### ISSUE TITLE
Consider publish a new version to crates.io which contains changes #388 made

### ISSUE THREAD

**Issue by Officeyutong** [libbpf/libbpf-rs#395]
#388 exposes underlying pointers of BpfObject and BpfMap, but the latest version `0.20` seems not containing the changes. So other crates which are published to crates.io cannot use the new future. Consider publish a new version to crates.io to fix this

**Comment by danielocfb** [comment]
Right, it didn't make the cut. Are you actively waiting for that or is this more a hypothetical? From my perspective it's a minor feature and I don't think we will ever get to a state at which we publish a new release after every commit. There is always the option of consuming a snapshot. That being said, the `0.20` took a long time and we will release somewhat more frequently in the future.

**Comment by Officeyutong** [comment]
> Right, it didn't make the cut. Are you actively waiting for that or is this more a hypothetical? From my perspective it's a minor feature and I don't think we will ever get to a state at which we publish a new release after every commit. There is always the option of consuming a snapshot. That being said, the `0.20` took a long time and we will release somewhat more frequently in the future.

Thank you! I'll wait for the next version.

**Comment by danielocfb** [comment]
> Thank you! I'll wait for the next version.

FYI, we just released `0.20.1`.
