### ISSUE TITLE
[RFC] Add trait for skeleton

### ISSUE THREAD

**Issue by chengshuyi** [libbpf/libbpf-rs#442]
Now builder, open and load return different data types. If traits are provided, we can treat them as general types, which is easier to use. The following are the available traits that I can think of. Any suggestions are welcome. Thanks!

```rust
pub trait SkelBuilder<'a> {
    type Output: OpenSkel;
    fn open(self) -> Result<Self::Output>;
    fn open_opts(self, open_opts: libbpf_sys::bpf_object_open_opts) -> Result<Self::Output>;
}


pub trait OpenSkel {
    type Output: Skel;
    fn load(self) -> Result<Self::Output>;
}

pub trait Skel {
    fn attach(&mut self) -> Result<()>;
    fn object(&self) -> &Object;
    fn object_mut(&mut self) -> &mut Object;
}
```

**Comment by danielocfb** [comment]
Hi @chengshuyi, I believe what you propose makes sense. Do you have plans to implement it?

**Comment by chengshuyi** [comment]
> Hi @chengshuyi, I believe what you propose makes sense. Do you have plans to implement it?

Yes, I will submit a PR this week. Thanks!

**Comment by danielocfb** [comment]
https://github.com/libbpf/libbpf-rs/pull/452 got merged.
