### ISSUE TITLE
Allow manipulating map of type queue or stack

### ISSUE THREAD

**Issue by ZhengjunHUO** [libbpf/libbpf-rs#463]
Hello,

I'm rewriting a cli implemented with Go based on cilium/ebpf to Rust, who applies firewall rules to container at cgroup level and monitoring the container's network flow. 
The latter feature engages a map type `queue` allowing the bpf program to record all ingress/egress info of the container which can be popped out to stdout by launching the cli.

But it seems like the lookup_and_delete method in libbpf_rs::Map doesn't yet support the operation on queue/stack, as mentioned in the comment and the outcome of my attempts.

**Comment by danielocfb** [comment]
With https://github.com/libbpf/libbpf-rs/pull/464 merged, I believe this issue can be closed. Let me know if something else should be covered.
