### ISSUE TITLE
Standalone map creation is involuted

### ISSUE THREAD

**Issue by gabibbo97** [libbpf/libbpf-rs#472]
Hello there, I was trying to create a standalone map like in the ` create_outer_array` example from https://docs.kernel.org/bpf/map_of_maps.html

The only interface I found is Map::create(), there the parameter bpf_map_create_opts directly refers to libbpf-sys.
I am not very sure about what each option does (I believe it acts like the __type and __uint from bpf_helpers.h).
Is there an easier way?

**Comment by danielocfb** [comment]
The C example:
```c
int create_outer_array(int inner_fd) {
        LIBBPF_OPTS(bpf_map_create_opts, opts, .inner_map_fd = inner_fd);
        int fd;

        fd = bpf_map_create(BPF_MAP_TYPE_ARRAY_OF_MAPS,
                            "example_array",       /* name */
                            sizeof(__u32),         /* key size */
                            sizeof(__u32),         /* value size */
                            256,                   /* max entries */
                            &opts);                /* create opts */
        return fd;
}
```
has `inner_map_fd` set in the create opts. So I would try setting that in the `&libbpf_sys::bpf_map_create_opts` argument to `Map::create`.

**Comment by danielocfb** [comment]
I assume the above explanation helped. I am not aware of an easier solution than what I stated. Closing.
