### ISSUE TITLE
Support for ringbuf?

### ISSUE THREAD

**Issue by willfindlay** [libbpf/libbpf-rs#49]
I noticed this crate seems to support the older perf buffer technique for passing per-event data to userspace but not the newer ringbuf map. Do you have plans to include this / would you be interested in a PR?

Thanks! Loving the crate so far.

**Comment by danobi** [comment]
It's not in my personal plans at the moment but I think it would be a great addition. PR is very welcome.

> Thanks! Loving the crate so far.

:)
