### ISSUE TITLE
Interacting with existing maps?

### ISSUE THREAD

**Issue by levaitamas** [libbpf/libbpf-rs#52]
Long story short: I want to use libbf-rs to interact with globally pinned maps that are not created by loading an object with libbpf-rs, but I can not find a way to do that.

Some context: I am working on a user space program which communicates with a bpf object loaded as a tc direct-action via bpf maps. My bpf object in kernel creates the maps, and pins them globally. So, the task for the user-space part is just to manipulate these existing maps. I came up with this design since I have not find any option to load my bpf object as a direct-action w/o using tc. 

Libbpf has a straightforward way to interact with existing maps: bpf_obj_get() returns the fd of the map, then the returned fd can be used for map operations.  Is there any way to do this with libbpf-rs?

Thanks!

**Comment by danobi** [comment]
I think we can probably add a `unsafe from_fd(fd: i32)` method. Would that help your use case?

**Comment by levaitamas** [comment]
That would be great. I got stuck at instantiating `Map` objects.

**Comment by levaitamas** [comment]
I do have a hackish implementation which works for map updates and lookups. But I am concerned about substituting the `ptr` with a null pointer.

```rust
pub fn from_fd(
    fd: i32,
    name: String,
    ty: libbpf_sys::bpf_map_type,
    key_size: u32,
    value_size: u32,
) -> Self {
    Map {
        fd,
        name,
        ty,
        key_size,
        value_size,
        ptr: std::ptr::null_mut(),
    }
}
```

**Comment by danobi** [comment]
Hmmm yeah, it seems difficult to implement `from_fd` correctly. The issue is that libbpf hides `struct bpf_map` definition so we cannot really recreate a pointer. And I don't believe you can recover all the information in a `struct bpf_map` from just an FD. So it's unlikely we can add this kind of API to libbpf either.

I think if you want continue with your design, you probably have to make some unsafe calls to `libbpf_sys::bpf_map_*_elem()`. I don't think that should be too bad.

**Comment by anakryiko** [comment]
libbpf provides `bpf_map__reuse_fd()` API to use pinned map by its FD. Wouldn't that work here?

**Comment by danobi** [comment]
> libbpf provides bpf_map__reuse_fd() API to use pinned map by its FD. Wouldn't that work here?

bpf_map__reuse_fd() takes an allocated `struct bpf_map *` in-param. Where do we get that from?

**Comment by anakryiko** [comment]
`bpf_object__open_mem()` gives `struct bpf_object *`, then `bpf_object__find_map_by_name(obj, "my_map")` give `struct bpf_map *`. Before `bpf_object__load()`, you do `bpf_map__reuse_fd()` and now your bpf_map "reuses" pinned map, no new map is created. So for libbpf-rs it would be: 1) get OpenMap, 2) OpenMap::reuse_fd or something like that, 3) OpenObject::load, 4) Map will point to pinned map.

Something like that would work?

**Comment by danobi** [comment]
Let's say application A created the map and application B wants to interact with the map. So B would need to declare a dummy map so that they could call `OpenMap::reuse_fd()` on it?

Is this a typical workflow?

**Comment by anakryiko** [comment]
Typically it's the same application (e.g., handling of BPF program code upgrades, while keeping the state in maps the same). And even if it's not, usually such map will be used from BPF side. So it's rarely "dummy".

But if you only need to work with pinned map from user-space, then I'd say using low-level APIs (bpf_map_update_elem) are the most straightforward way.
