### ISSUE TITLE
Missing support for BPF_PROG_RUN

### ISSUE THREAD

**Issue by danobi** [libbpf/libbpf-rs#537]
`BPF_PROG_RUN` is quite useful for "unit testing" (integration testing if you're being pedantic). It looks like `Program` is missing support for it.

**Comment by danobi** [comment]
Each prog type has a different context. I'm wondering if we should provide definitions for all of them or just take a `T: Sized`. When I did this for cilium/ebpf we did the `interface{}` approach, as ctx definitions get quite hairy.

I suppose we could start with a `T: Sized` approach and also provide a few defs. That way we have some baked in forward compat.

WDYT?

**Comment by danielocfb** [comment]
> I suppose we could start with a `T: Sized` approach and also provide a few defs. That way we have some baked in forward compat.

That sounds good to me.
