### ISSUE TITLE
Skeleton generation issues with short filename + global variables

### ISSUE THREAD

**Issue by willfindlay** [libbpf/libbpf-rs#57]
This is something I noticed while I was working on my personal project based on libbpf-rs. When I have a very short BPF source file name and global variables, the resulting skeleton generates incorrectly, such that there is a name mismatch between the generated map name and the generated skeleton name.

The above may be a bit confusing, so I'll illustrate with an example:

**src/bpf/ebph.bpf.c:**
```c
/* ... */
volatile const int ebph_logging;
/* ... */
```
**src/bpf/ebph_skel.rs:**
```rust
fn build_skel_config() -> libbpf_rs::Result<libbpf_rs::skeleton::ObjectSkeletonConfig<'static>> {
    let mut builder = libbpf_rs::skeleton::ObjectSkeletonConfigBuilder::new(DATA);
    builder
        .name("ebph_bpf")
        .map("__profile_key_t__alloc", false)
        .map("__profile_key_t__temp", false)
        .map("profiles", false)
        .map("ebph.rodata", true)
        .prog("bprm_check_security");

    builder.build()
}
```

Note that `name` is `ebph_bpf` but we have `ebph.rodata`. In the libbpf debug logs, we can see the problem:
```
libbpf: map 'ebph_bpf.rodata' (global data): at sec_idx 6, offset 0, flags 480.
libbpf: map 3 is "ebph_bpf.rodata"
(...)
libbpf: failed to find skeleton map 'ebph.rodata'
```
If I go into the generated skeleton and manually update to either `.name("ebph")` or `.map("ebph_bpf.rodata")`, we get the expected result. With longer program names, the `_bpf` part gets cut off and we get the expected result as well. You can see this in runqslower for example:
```rust
fn build_skel_config() -> libbpf_rs::Result<libbpf_rs::skeleton::ObjectSkeletonConfig<'static>> {
    let mut builder = libbpf_rs::skeleton::ObjectSkeletonConfigBuilder::new(DATA);
    builder
        .name("runqslower_bpf")
        .map("start", false)
        .map("events", false)
        .map("runqslow.rodata", true)
        .prog("handle__sched_wakeup")
        .prog("handle__sched_wakeup_new")
        .prog("handle__sched_switch");

    builder.build()
}
```

I haven't had a chance to look at the skeleton generation code yet, but I suspect there is a trivial fix.

**Comment by willfindlay** [comment]
Seems like we can just remove the `_bpf` part from `gen.rs` like so:
```diff
diff --git a/libbpf-cargo/src/gen.rs b/libbpf-cargo/src/gen.rs
index 3c8486f..643bfd9 100644
--- a/libbpf-cargo/src/gen.rs
+++ b/libbpf-cargo/src/gen.rs
@@ -165,7 +165,7 @@ fn gen_skel_c_skel_constructor(
         {{
             let mut builder = libbpf_rs::skeleton::ObjectSkeletonConfigBuilder::new(DATA);
             builder
-                .name("{name}_bpf")
+                .name("{name}")
         "#,
         name = name
     )?;

```
Is there any specific reason why the `_bpf` was included in the first place? If not, I can make a PR.

**Comment by danobi** [comment]
> Seems like we can just remove the _bpf part from gen.rs like so:

I *think* I was following convention from bpftool: https://github.com/torvalds/linux/blob/6ee1d745b7c9fd573fba142a2efdad76a9f1cb04/tools/bpf/bpftool/gen.c#L482 , where bpftool takes the .o filename, strips the `.o` and replaces the `.bpf` with `_bpf`.

Does applying your diff fix your issue?

**Comment by danobi** [comment]
Can you upload your `.bpf.o` here so I can try reproducing?

**Comment by willfindlay** [comment]
> Does applying your diff fix your issue?
It does.

**Comment by willfindlay** [comment]
> Can you upload your `.bpf.o` here so I can try reproducing?

My project is quite large at this point, so I'll just create a minimal example for you instead. I'll also create a PR with my change in the meantime.

**Comment by willfindlay** [comment]
@danobi Here's a gzipped tarball with my minimal object file.

[test.bpf.o.tar.gz](https://github.com/libbpf/libbpf-rs/files/5869672/test.bpf.o.tar.gz)
