### ISSUE TITLE
support for manipulating btf

### ISSUE THREAD

**Issue by dvc94ch** [libbpf/libbpf-rs#58]
I'm currently trying to symbolize my kernel stack trace. It seems that `/system/kernel/btf/vmlinux` needs to be parsed and that `libbpf` and `libbpf-cargo` have support for it, but not `libbpf-rs`.

**Comment by danobi** [comment]
Right, there's some basic BTF support in libbpf-cargo. I made sure it wasn't a total hack so it could become public API one day, but I think there's still some more work to be done before making it an API.

For one, I'd like to replace all the ID fields with `BtfType`s. That'd probably take an extra pass in `Btf::new()` but it'd make working with BTF so much nicer.

**Comment by anakryiko** [comment]
How BTF would help you with symbolization of kernel stack traces? It doesn't record function addresses at all. What you need is to parse /proc/kallsyms. See https://github.com/iovisor/bcc/blob/master/libbpf-tools/trace_helpers.c#L160

**Comment by anakryiko** [comment]
> Right, there's some basic BTF support in libbpf-cargo. I made sure it wasn't a total hack so it could become public API one day, but I think there's still some more work to be done before making it an API.
> 
> For one, I'd like to replace all the ID fields (eg
> 
> https://github.com/libbpf/libbpf-rs/blob/7176f1c1586a5d4227e82ce81cf821226bcb8506/libbpf-cargo/src/btf/types.rs#L58
> ) with `BtfType`s. That'd probably take an extra pass in `Btf::new()` but it'd make working with BTF so much nicer.

You mean have a direct reference to another type? I wonder how will look like with all the lifetimes and stuff. And how will it interact with mutable BTF? I found it so much easier to stick with IDs in Rust.

**Comment by dvc94ch** [comment]
Done https://github.com/dvc94ch/rust-bpf/blob/master/bpf-utils/src/kallsyms.rs, so how would you symbolize a user stack trace? Parse `/proc/{pid}/maps` match on the address range, get the file name in the last column and try to load debug info from that file?

**Comment by anakryiko** [comment]
Check what BCC is doing, it has support for symbolizing user-space stack traces. There are few different ways, with various supported features (e.g, inlined function support will need expensive DWARF parsing), etc.

**Comment by danobi** [comment]
> So how would you symbolize a user stack trace? Parse /proc/{pid}/maps match on the address range, get the file name in the last column and try to load debug info from that file?

IIRC the way bpftrace does it (it uses bcc for some parts) is:
* collect/send pid+stack in bpf prog to userspace
* userspace extracts pid from stack
* userspace opens /proc/pid/exe and then walks the symbol table for each addr in the stack

**Comment by danobi** [comment]
> (e.g, inlined function support will need expensive DWARF parsing), etc.

I think the only way to DWARF walk a stack is to copy large segments of the stack from prog -> userspace. And that would be quite expensive, indeed

**Comment by anakryiko** [comment]
No-no, DWARF just has a special encoding for inlined functions, which is CPU-intensive to process and look up. I don't think anyone is copying lots of stack, normal stack traces are OK. You'll just end up mapping single IP into multiple functions (all but one will be inlined functions). I think you are confusing this with capturing stack trace when there are no frame pointers. That's a very different problem.

**Comment by dvc94ch** [comment]
Yes, currently the problem is how to symbolize (find line numbers for an address) a stack trace (array of instruction pointers). Bpf has a `bpf_get_stackid` helper that walks the stack in the kernel when frame pointers are enabled. To walk the stack without frame pointers I think the dwarf `.eh_frame` section could be compiled into a bpf stack walking program based on https://github.com/frdwarf/dwarf-assembly, but that isn't the "problem" yet.

**Comment by danobi** [comment]
>  I don't think anyone is copying lots of stack, 

I believe `perf` does that if you ask it to do DWARF walks. But not through bpf

> You mean have a direct reference to another type? I wonder how will look like with all the lifetimes and stuff. And how will it interact with mutable BTF? I found it so much easier to stick with IDs in Rust.

I'm not 100% sure (would need to experiment) but it should be OK to do direct references to another type if it's all readonly. And it most likely has to stay read only b/c the rust types are not laid out the same as the underlying C types. So there would have to be an API for mutation. And maybe the mutation API can force invalidation of read only handles and returns new handles after mutation.

> Yes, currently the problem is how to symbolize (find line numbers for an address) a stack trace (array of instruction pointers)

Getting line numbers sound hard -- is that a strict requirement? Would be far easier to just get function names.

> To walk the stack without frame pointers I think the dwarf .eh_frame section could be compiled into a bpf stack walking program based on https://github.com/frdwarf/dwarf-assembly, but that isn't the "problem" yet.

Not sure that's possible today but I'm willing to be surprised :).

**Comment by dvc94ch** [comment]
> Getting line numbers sound hard -- is that a strict requirement? Would be far easier to just get function names.

Why is that easier? From my current understanding these steps are required to symbolize a user space stack trace and I'm not aware of any "shortcuts":

1. parse `/proc/{pid}/maps`
2. for each address lookup the exe/so mapped to that range and subtract the start of the range to get the relative address
3. locate the dwarf debug info for the elf file using either
  - the debug info is in the binary
  - the binary contains a build-id that can be used to locate the debug info
  - the binary contains a debug-link that can be used to locate the debug info
4. parse the debug info and get the line number (the easy part as we have a nice rust library for that called gimli)

for my particular use case (I'm interested in building tools to analyze why my rust programs block) the debug info is always in the binary. But I guess I still need to go through all those steps as most rust binaries are linked agains glibc.

**Comment by dvc94ch** [comment]
One think I find a bit unreliable is the first step. What if the program loads an `so` during runtime? So I can't read it when the program starts. What if the program unloads an `so` during runtime? I can't read it before the program ends either.

**Comment by anakryiko** [comment]
> > Getting line numbers sound hard -- is that a strict requirement? Would be far easier to just get function names.
> 
> Why is that easier? From my current understanding these steps are required to symbolize a user space stack trace and I'm not aware of any "shortcuts":

Well, it's easier and much faster to just parse SYMTAB to get all the function symbols and just use that for stack symbolization. So if you don't need line numbers, you don't need DWARF at all.

> One think I find a bit unreliable is the first step.

BPF allows to capture build_id in stack trace, which you can use to find DWARF even after application exited or library got unloaded. But that assumes you can locate the binary by its build_id, of course.

**Comment by dvc94ch** [comment]
Looks like I won't get very far with frame pointers, I can't get rust to keep them around. Looks like I'll have to try compiling `.eh_frame` into a bpf program sooner than I thought.

Below is the output from an example in my bpf library in case you're curious about what it can do. The first section prints the `build-id`, `exe-path`, `debug-info-path` of all the stuff that will be loaded into the process.

```sh
be71510a6a27798660c8987493ea0ed01f3d6734 /usr/lib/libgcc_s.so.1 /usr/lib/libgcc_s.so.1
8aeb7ef55bf4ee61c09907bb5c0e2b1767ebc26f /usr/lib/libdl-2.32.so
87f011a7e4cc3fc60a54d0d3dd690e7438decc8d /usr/lib/libc-2.32.so
c759fb7ac534bf7a111d95e1bbc43c93734a4680 /usr/lib/libpthread-2.32.so
9242baeb7dca270a379b3cf89c2ea496d9b92524 /usr/lib/ld-2.32.so
40edea1f9d1040312eea0131972804eb56dc84bf /home/dvc/ipld/rbpf/target/debug/examples/hello_world /home/dvc/ipld/rbpf/target/debug/examples/hello_world

libbpf: elf: skipping unrecognized data section(8) .eh_frame
libbpf: elf: skipping relo section(9) .rel.eh_frame for section(8) .eh_frame
hello world!
ustack observed 1 times:
  0: 0x55ff271c97b4
ustack observed 1 times:
  0: 0x55ff271faa6a
ustack observed 1 times:
  0: 0x55ff271faef0
ustack observed 2 times:
  0: 0x55ff271cea1c
ustack observed 1 times:
  0: 0x55ff271fad20
ustack observed 1 times:
  0: 0x55ff271c9468
ustack observed 1 times:
  0: 0x55ff271f9dec
```

**Comment by dvc94ch** [comment]
So I wrote a eh_frame to bpf compiler [0]. Saddly I'm hitting the 512 byte stack limit. So unless there is a way to disable it, the kernel will need to gain some assistance. Do you think that the kernel devs would welcome a new unwinder based on `.eh_elf` as described in "Reliable and fast dwarf-based stack unwinding"? [1]

- [0] https://github.com/dvc94ch/ehframe-bpf-compiler
- [1] https://hal.inria.fr/hal-02297690/document

**Comment by danobi** [comment]
> Saddly I'm hitting the 512 byte stack limit. 

Should be fairly trivial to workaround stack limit by using a map. Have you tried that?

> Do you think that the kernel devs would welcome a new unwinder based on .eh_elf as described in "Reliable and fast dwarf-based stack unwinding"? [1]

Last I heard Linus was really against DWARF based unwinding. Which is why the kernel has ORC. Maybe look into what happened to this attempt: https://lkml.org/lkml/2017/5/5/571

**Comment by dvc94ch** [comment]
I'm not actually reaching the stack limit I don't think. It's a really long binary search on the pc, so the generated code looks like this:

```rust
if pc < 0x8888 {
   if pc < 0x4444 {
   } else {
   }
} else {
  if pc < 0xcccc {
  } else {
  }
}
```
So I don't really know why clang thinks I'm using a lot of stack.

**Comment by dvc94ch** [comment]
Also linus objected to the use of dwarf unwinding for kernel stack traces. I don't see it necessarily being a problem for user stack traces? And I also didn't propose adding a dwarf unwinder [0]. It is also not required to have a full dwarf unwinder as neither clang/gcc or rustc use all the possibilities that dwarf allows for. In a preprocessing or precompilation step we can easily make sure that only a very simplified subset is used. I think there are two options. Either extend the orc unwinder to make it suitable for unwinding user space programs or add a new unwinder based on `.eh_elf` that just exports a `fn eh_elf(pc, rsp, rbp, rbx) -> (pc, rsp, rbp, rbx)`. For the second option the only thing that the kernel would have to do is call `eh_elf` in a loop until `rsp == 0xFFFFFFFF` and record all the pc values.

- [0] https://github.com/frdwarf/dwarf-assembly/issues/2

**Comment by anakryiko** [comment]
Instead of unrolled nested if/else checks, have you tried writing this binary search as a pretty straightforward BPF loop with a limit on number of iterations (20 would give you 1mln items support, so that seems plenty). And then supply actual frame data as a map or global variable?

**Comment by dvc94ch** [comment]
so my tool cargo-trace seems to be able to capture stack traces up to a length of 24 and binary search depth of 16. Looks like things like inline assembly and c code still don't quite work.

```
stack observed 1 times:
   0: core::cmp::impls::<impl core::cmp::PartialOrd for i32>::lt
             at /rustc/14b27555a03f4abf9b8d80ea34f59144e2ded5e4/library/core/src/cmp.rs:1258
   1: core::iter::range::<impl core::iter::traits::iterator::Iterator for core::ops::range::Range<A>>::next
             at /rustc/14b27555a03f4abf9b8d80ea34f59144e2ded5e4/library/core/src/iter/range.rs:507:12
   2: fill_stack::stack_filled
             at /home/dvc/ipld/cargo-trace/bpf-backtrace/examples/fill_stack.rs:35:14
   3: fill_stack::fill_my_stack1
             at /home/dvc/ipld/cargo-trace/bpf-backtrace/examples/fill_stack.rs:8:9
   4: fill_stack::fill_my_stack2
             at /home/dvc/ipld/cargo-trace/bpf-backtrace/examples/fill_stack.rs:15:5
   5: fill_stack::fill_my_stack1
             at /home/dvc/ipld/cargo-trace/bpf-backtrace/examples/fill_stack.rs:7:5
   6: fill_stack::fill_my_stack2
             at /home/dvc/ipld/cargo-trace/bpf-backtrace/examples/fill_stack.rs:15:5
   7: fill_stack::fill_my_stack1
             at /home/dvc/ipld/cargo-trace/bpf-backtrace/examples/fill_stack.rs:7:5
   8: fill_stack::fill_my_stack2
             at /home/dvc/ipld/cargo-trace/bpf-backtrace/examples/fill_stack.rs:15:5
   9: fill_stack::fill_my_stack1
             at /home/dvc/ipld/cargo-trace/bpf-backtrace/examples/fill_stack.rs:7:5
  10: fill_stack::fill_my_stack2
             at /home/dvc/ipld/cargo-trace/bpf-backtrace/examples/fill_stack.rs:15:5
  11: fill_stack::fill_my_stack1
             at /home/dvc/ipld/cargo-trace/bpf-backtrace/examples/fill_stack.rs:7:5
  12: fill_stack::fill_my_stack2
             at /home/dvc/ipld/cargo-trace/bpf-backtrace/examples/fill_stack.rs:15:5
  13: fill_stack::fill_my_stack1
             at /home/dvc/ipld/cargo-trace/bpf-backtrace/examples/fill_stack.rs:7:5
  14: fill_stack::main
             at /home/dvc/ipld/cargo-trace/bpf-backtrace/examples/fill_stack.rs:4:2
  15: core::ops::function::FnOnce::call_once
             at /rustc/14b27555a03f4abf9b8d80ea34f59144e2ded5e4/library/core/src/ops/function.rs:227:5
  16: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/14b27555a03f4abf9b8d80ea34f59144e2ded5e4/library/std/src/sys_common/backtrace.rs:128:5
  17: std::rt::lang_start::{{closure}}
             at /rustc/14b27555a03f4abf9b8d80ea34f59144e2ded5e4/library/std/src/rt.rs:66:18
  18: std::panicking::try
             at /rustc/14b27555a03f4abf9b8d80ea34f59144e2ded5e4/library/std/src/panicking.rs:344:13
    : std::panic::catch_unwind
             at /rustc/14b27555a03f4abf9b8d80ea34f59144e2ded5e4/library/std/src/panic.rs:431:14
    : std::rt::lang_start_internal
             at /rustc/14b27555a03f4abf9b8d80ea34f59144e2ded5e4/library/std/src/rt.rs:51:25
  19: std::rt::lang_start
             at /rustc/14b27555a03f4abf9b8d80ea34f59144e2ded5e4/library/std/src/rt.rs:65:5
  20: 0x3534a
  21: 0x7ffff7db6b25
  22: 0x7fffffffe518
  23: 0x1f7fca000
```

**Comment by dvc94ch** [comment]
Sorry to bother you guys again, but you've been by far the most helpful so far :) and I can not figure out how to post to the bpf mailing list, which I assume is intended as it avoids spam.

The current problem I have with `cargo-trace` is unwinding the user space stack when a kprobe is triggered. The difficulty is that the pt_regs are not the user space ones. So you need to get the task_struct using the `bpf_get_task_struct` helper and then get the stack field. This may seem easy but for various reasons it is not:

- task_struct isn't in the uapi headers and it is virtually impossible to use non uapi headers outside of the kernel, or at least I'm finding it very hard
- there is a `randomized_struct_fields_start` in the `task_struct` which seems to let gcc insert a random offset per build so I can't create a task_struct that mimicks the layout and use that to compute the offset to the stack field.

any ideas on what the best way to do this is?

**Comment by danobi** [comment]
> task_struct isn't in the uapi headers and it is virtually impossible to use non uapi headers outside of the kernel, or at least I'm finding it very hard

I think you can  use `BPF_CORE_READ(..)` to get your field reliably.

> there is a randomized_struct_fields_start in the task_struct which seems to let gcc insert a random offset per build so I can't create a task_struct that mimicks the layout and use that to compute the offset to the stack field.

You'll probably need to disable that kernel config option. IIRC (I think I saw some discussion a long time ago about this) you cannot use struct layout randomization and BTF -- they are antithetical to each other.
