### ISSUE TITLE
Using BPF_MAP_TYPE_LPM_TRIE in libbpf-rs

### ISSUE THREAD

**Issue by syogaraj** [libbpf/libbpf-rs#586]
Hi there,
I have a doubt about using the LPM_TRIE map in the bpf program using libbpf-rs.
This experiment aims to look up the source IP for incoming packets (via xdp) in the bpf map and decide whether to allow/deny them. 
I have defined a LPM map as below,

```
//filter.bpf.c

struct ipv4_lpm_key {
	__u32 prefixlen;
	__u32 data;
};

struct {
	__uint(type, BPF_MAP_TYPE_LPM_TRIE);
	__type(key, struct ipv4_lpm_key);
	__type(value, __u32);
	__uint(map_flags, BPF_F_NO_PREALLOC);
	__uint(max_entries, 255);
} ipv4_lpm_map SEC(".maps");
```

I want to pre-populate the map in the userspace program `main.rs` before attaching it to xdp.
Example: Updating `192.168.1.0/24` in the lpm map.
```
let v4_key = filter_bss_types::ipv4_lpm_key {
                prefixlen: 24,
                data: 0xc0a80100_u32.to_be(),  
            };
```
How do I convert this `v4_key` to `[u8; 8]`? Are there any examples of this and please suggest if there are any alternate ways to populate the maps?

**Comment by syogaraj** [comment]
@danielocfb, I've tried transmuting the value before, in which I got the below error. 
`Error: System error, errno: 22 (EINVAL: Invalid argument)` 

Below is the code that I used to transmute and update the values in the map. 

```
let key: [u8; 8] = unsafe { transmute(0xc0a80100_u32.to_be() as u64) };
let value: [u8; 4] = unsafe { transmute(1) };

skel.maps_mut()
       .ipv4_lpm_map()
       .update(&key, &value, MapFlags::ANY)?;
```

**Comment by danobi** [comment]
@syogaraj It's been a bit since I've worked with the lpm trie map, but I think you might have yours bytes backwards: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=cabc7329521436823bb30611b2eed1e2

IOW, I think the 0's in the array need to be first.

**Comment by syogaraj** [comment]
Thanks for pointing that out @danobi. 

Using `plain::as_bytes(&v4_key)` worked. Thanks @danielocfb! I was able to populate the map and query the map using `bpftool map lookup` command. 

When tried the same with the bpf code, I always get the value as `0`. Any ideas on this? 

```
__u32 defined;
__u32 source = bpf_htonl(iphdr->saddr);
bpf_printk("ipv4 source: %x, %d, %pI4", source, source, source);

struct ipv4_lpm_key key = { .prefixlen = 32, .data = source };
defined = bpf_map_lookup_elem(&ipv4_lpm_map, &key);
```

### bpf trace print:
```
# cat /sys/kernel/debug/tracing/trace_pipe
<idle>-0       [008] d.s31 3467808.153072: bpf_trace_printk: ipv4 source: 7f000001, 2130706433, 0.0.0.0
Chrome_ChildIOT-2100990 [009] d.s21 3467809.657061: bpf_trace_printk: ipv4 source: 7f000001, 2130706433, 0.0.0.0
```

### bpftool dump:
```
# bpftool map dump id 1158
[{
        "key": {
            "prefixlen": 8,
            "data": 2130706432
        },
        "value": 2
    }
]
```

### bpftool lookup:
```
# bpftool map lookup id 1158 key 0x20 0x00 0x00 0x7f 0x00 0x00 0x00 0x01 
{
    "key": {
        "prefixlen": 2130706464,
        "data": 16777216
    },
    "value": 2
}
```

**Comment by danobi** [comment]
Where is `iphdr` coming from? Also if you code is doing:

```
__u32 source = bpf_htonl(iphdr->saddr);
bpf_printk("ipv4 source: %x, %d, %pI4", source, source, source);
```

then the lpm trie is irrelevant, right?

**Comment by syogaraj** [comment]
> Where is iphdr coming from?

`iphdr` comes from the `parse_iphdr` function.

```
//reference from https://github.com/xdp-project/xdp-tools/blob/master/headers/xdp/parsing_helpers.h

static __always_inline int parse_iphdr(struct hdr_cursor *nh,
				       void *data_end,
				       struct iphdr **iphdr)
{
	struct iphdr *iph = (struct iphdr *)nh->pos;
	int hdrsize;

	if (iph + 1 > data_end)
		return -1;

	hdrsize = iph->ihl * 4;

	if (nh->pos + hdrsize > data_end)
		return -1;

	nh->pos += hdrsize;
	*iphdr = iph;

	return iph->protocol;
}
```

```
//filter.bpf.c

if (eth_type == bpf_htons(ETH_P_IP)) {
      ip_type = parse_iphdr(&nh, data_end, &iphdr);
      CHECK_RET(ip_type);   // checks if ip_type < 0, then XDP_ABORTED
      __u32 source = bpf_htonl(iphdr->saddr);
      bpf_printk("ipv4 source: %x, %d, %pI4", source, source, source);
      
      struct ipv4_lpm_key key = { .prefixlen = 32, .data = source };
      defined = bpf_map_lookup_elem(&ipv4_lpm_map, &key);
}
```

> then the lpm trie is irrelevant, right?

The print statements are made for debugging purposes. I still need to lpm trie to check whether the incoming IP is allowed or not against the configured prefixes.
