### ISSUE TITLE
Support bpf_map_update_batch method

### ISSUE THREAD

**Issue by syogaraj** [libbpf/libbpf-rs#607]
``` 
LIBBPF_API int bpf_map_update_batch (int fd, const void *keys, const void *values, __u32 *count, const struct bpf_map_batch_opts *opts)
```

The above-mentioned API is missing from the `MapHandle` in `map.rs` implementation. 
I want to work on this. Would someone be able to give me a green or are there any blockers for this?

**Comment by danielocfb** [comment]
Hi @syogaraj , I am not aware of any blockers. Feel free to go ahead and/or reach out if you encounter problems.

**Comment by danielocfb** [comment]
Hi @syogaraj, please let us know if you need help with this support.

**Comment by syogaraj** [comment]
@danielocfb will open a PR by today or tomorrow. 
Can you share some guidelines on how to write tests for this API?

**Comment by chantra** [comment]
@syogaraj  maybe something similar to https://github.com/libbpf/libbpf-rs/blob/855eb8422e98e4632d433d5fbf065ab703674fbf/libbpf-rs/tests/test.rs#L1070 ?
