### ISSUE TITLE
Accessing the memory-mapped region of a BPF map

### ISSUE THREAD

**Issue by V0ldek** [libbpf/libbpf-rs#608]
How can I access the memory-mapped BPF map (with the `BPF_F_MMAPABLE` flag)?

I can see that libbpf creates a memory map when loading my BPF object, but I can't see how to get that slice/pointer from the public API. All I can do is get a file descriptor of the map.

That pointer lives somewhere, in the C libbpf library it seems to be in the `mmaped` field of `bpf_map`. How do I get that from Rust code?

**Comment by anakryiko** [comment]
libbpf gives access to this mmaped memory for global variables maps (.data, .bss, .rodata) through bpf_map__initial_value() (https://github.com/libbpf/libbpf/blob/master/src/libbpf.h#L996-L998). But in general, you can mmap() your map's BPF_F_MMAPABLE data area yourself, if you have custom ARRAY map with BPF_F_MMAPABLE flag.

**Comment by V0ldek** [comment]
> But in general, you can mmap() your map's BPF_F_MMAPABLE data area yourself

That's true, but that'll create a second mapping, am I correct? If I call `mmap` myself on the map's file descriptor it'll create a new memory mapping, but one is already created by libbpf on program load... So it'd be a minor waste of resources?

**Comment by anakryiko** [comment]
libbpf creates memory mapping only for .data/.bss/.rodata global variables maps. If you have your own ARRAY map with BPF_F_MMAPABLE, libbpf won't try to mmap() it automatically.

**Comment by d-e-s-o** [comment]
@V0ldek I trust that Andrii's response addressed your question, so I am going to close this issue. If that's not the case then please reopen/respond.
