### ISSUE TITLE
Document purpose of "custom" hook for TcHook

### ISSUE THREAD

**Issue by valkmit** [libbpf/libbpf-rs#616]
https://github.com/libbpf/libbpf-rs/blob/855eb8422e98e4632d433d5fbf065ab703674fbf/examples/tc_port_whitelist/src/main.rs#L83-L92

It's unclear to me based on this example why a custom hook is necessary to attach to tc ingress. Is there any additional documentation that you could point me to to understand why?

**Comment by danielocfb** [comment]
Perhaps @mmullin-halcyon may know?

**Comment by mmullin-halcyon** [comment]
BPF_TC_CUSTOM filters all need a parent as per the bpf_tc_attach() documentation here:

https://lwn.net/ml/bpf/20210512103451.989420-3-memxor@gmail.com/

When we dive into the libbpf code function `bpf_tc_attach` (https://elixir.bootlin.com/linux/latest/source/tools/lib/bpf/netlink.c#L718) we see that `tc_get_tcm_parent()` is called (line 761).  This function will error if a BPF_TC_CUSTOM does NOT have a parent, or a BPF_TC_INGRESS/EGRESS does have a parent.
