### ISSUE TITLE
Separate mod for Xdp

### ISSUE THREAD

**Issue by syogaraj** [libbpf/libbpf-rs#618]
Hi,

Can we have a separate mod for xdp (say `xdp.rs`) similar to what we have for `tc`? Below are the functional specs that I've worked out for this. This will also help catch up with the [feature parity with libbpf-1.0](https://github.com/libbpf/libbpf-rs/milestone/1). I do have some doubts about the API in libbpf and kindly suggest improvements if any.

Struct:
```
struct Xdp {
      fd: BorrowedFd,
      attach_opts: libbpf_sys::bpf_xdp_attach_opts,
      query_opts: libbpf_sys::bpf_xdp_query_opts,
}
```

Methods:
| Method Name | Args | libbpf-API |
|--------|--------|--------|
| attach | ifindex, flags, attach_opts |  `bpf_xdp_attach` |
| detach | ifindex, flags, attach_opts | `bpf_xdp_detach` |
| query | ifindex, flags, query_opts | `bpf_xdp_query` |
| query_id | ifindex, flags, prog_id | `bpf_xdp_query_id` | 

Need clarifications for the following:
1. Would it make sense to move the ifindex to the struct itself? 
2. Can we have a `XDPBuilder` similar to `TcHookBuilder`? I don't see any requirements for this. Just asking though.
3. `bpf_xdp_attach_opts`: attribute `old_prog_fd` - I guess this is used in combination with `libbpf_sys::XDP_FLAGS_REPLACE`. If this is correct, we should have a method for `replace` as well.
4. `bpf_xdp_query_opts`: How to expose an API for this to use the `query` method?

**Comment by danielocfb** [comment]
Sounds reasonable to me.

> Need clarifications for the following:
> 
> 1. Would it make sense to move the ifindex to the struct itself?

If it's required for all operations then this would make sense, I think.

> 2. Can we have a `XDPBuilder` similar to `TcHookBuilder`? I don't see any requirements for this. Just asking though.

We should probably have a use case for it to motivate the introduction.

> 3. `bpf_xdp_attach_opts`: attribute `old_prog_fd` - I guess this is used in combination with `libbpf_sys::XDP_FLAGS_REPLACE`. If this is correct, we should have a method for `replace` as well.

I am not familiar with the attribute. Sounds like a `libbpf` question, so perhaps @anakryiko would know?

> 4. `bpf_xdp_query_opts`: How to expose an API for this to use the `query` method?

I'd go with something similar to what we do for Tc, unless there are good reasons to diverge. Have you found any?

**Comment by anakryiko** [comment]
> Sounds reasonable to me.
> 
> > Need clarifications for the following:
> > 
> > 1. Would it make sense to move the ifindex to the struct itself?
> 
> If it's required for all operations then this would make sense, I think.

libbpf's approach to this is that any required argument (and also frequently specified ones) is passed as an explicit argument, while all the optional stuff goes into opts struct

> 
> > 3. `bpf_xdp_attach_opts`: attribute `old_prog_fd` - I guess this is used in combination with `libbpf_sys::XDP_FLAGS_REPLACE`. If this is correct, we should have a method for `replace` as well.
> 
> I am not familiar with the attribute. Sounds like a `libbpf` question, so perhaps @anakryiko would know?

yes, old_prog_fd seems to go together with XDP_FLAGS_REPLACE. On libbpf side we chose not to do a dedicated replace API, though. Which isn't to say that libbpf-rs shouldn't do it. But as far as I'm concerned, these bpf_xdp_{attach,detach} APIs are quite low-level (we have higher-level bpf_program__attach_xdp() that uses BPF link in the kernel and in libbpf API), so adding extra nicety wrappers seemed inappropriate here.
