### ISSUE TITLE
Feature Request: Expose libbpf-cargo BPF object and skeleton generation code as a library

### ISSUE THREAD

**Issue by willfindlay** [libbpf/libbpf-rs#63]
Crates like [bindgen](https://rust-lang.github.io/rust-bindgen/) often expose code generation functionality via a builder pattern which can then be easily integrated into a project's build.rs file. I have found myself wanting to do something similar with libbpf-rs in one of my large projects, so it would be nice if this crate offered something similar.

Currently, as a workaround, I am just invoking the libbpf-cargo CLI from my build.rs, but obviously this is not ideal.

**Comment by danobi** [comment]
Yeah that seems totally reasonable. I've used bindgen before and I preferred the API over the CLI too.
