### ISSUE TITLE
Example fails with prog 'profile': invalid perf event FD -1

### ISSUE THREAD

**Issue by ikalchev** [libbpf/libbpf-rs#644]
Hi everyone,

I copied [this example](https://github.com/libbpf/libbpf-bootstrap/tree/master/examples/rust/profile) exactly and it builds fine. However, when running it, it fails as follows:

```
~/rust_profile$ sudo ./target/debug/profile
libbpf: prog 'profile': invalid perf event FD -1
```

Before I tried that, I was actually trying to sample a specific pid and based on cpu frequency, like:
```
// This uses a different "syscall" bindings to the ones above, but should be identical in the end. 
fn init_profiler(frequency: u64, process_pid: i32) -> i32 {
    let mut attr = syscall::perf_event_attr::default();
    attr.type_ = syscall::perf_type_id_PERF_TYPE_SOFTWARE;
    attr.size = mem::size_of::<syscall::perf_event_attr>() as u32;
    attr.config = syscall::perf_sw_ids_PERF_COUNT_SW_CPU_CLOCK as u64;
    attr.set_freq(1);
    attr.__bindgen_anon_1.sample_freq = frequency;
    attr.sample_type = syscall::perf_event_sample_format_PERF_SAMPLE_RAW;

    let fd = unsafe {
        syscall::perf_event_open(&mut attr, process_pid, -1, -1, 0)
    };
    println!("PEFD: {fd}");
    fd as i32
}

fn attach_perf_event(
    pefds: &[i32],
    program: &mut libbpf_rs::Program,
) -> Vec<Result<libbpf_rs::Link, libbpf_rs::Error>> {
    pefds
        .iter()
        .map(|pefd| program.attach_perf_event(*pefd))
        .collect()
}
```

This does not fail and gets a valid PEFD, but I cannot get the actual probe to do anything (as it if it is not running). The probe itself is:

```
#include "vmlinux.h"
#include <bpf/bpf_helpers.h>

char LICENSE[] SEC("license") = "GPL";


SEC("perf_event")
int bootstrap(void *ctx)
{
    bpf_printk("Bootstrap!");
    return 0;
}

SEC("perf_event")
int decode_frame_and_maybe_repeat(void *ctx)
{
    bpf_printk("Start: single frame decoding");
    return 0;
}
```

I am running all this on a Ubuntu VM under macOS on ARM
```
~/rust_profile$ uname -a
Linux xdp-test 6.2.0-39-generic #40~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 16 12:53:29 UTC 2 aarch64 aarch64 aarch64 GNU/Linux
```

Let me know if additional parts of the code would help debugging this or if I can troubleshoot anything else.

**Comment by danielocfb** [comment]
It seems as if `perf_event_open` is returning an error code and we do not check the result properly. Will see if we can fix that. You'll have to see why it fails on your system.

**Comment by danielocfb** [comment]
> You'll have to see why it fails on your system.

My guess would be the non-availability of hardware counters in your VM.

**Comment by danielocfb** [comment]
Can you check with https://github.com/libbpf/libbpf-bootstrap/pull/246 ? That should tell you that `perf_event_open` failed.

**Comment by ikalchev** [comment]
Thanks for the quick turnaround, I appreciate it. Will check that when I logon later.

And do you have any idea why the "software" probe doesn't seem to work? Or ideas on how can I troubleshoot it?

**Comment by danielocfb** [comment]
> And do you have any idea why the "software" probe doesn't seem to work? Or ideas on how can I troubleshoot it?

Not sure. It seemed to work when I tried it with the `profile` example.

**Comment by ikalchev** [comment]
I passed `flags=PERF_FLAG_FD_CLOEXEC` to the `perf_event_open` call and it worked (used to be 0). Maybe the defaults are different on aarch64?

I will check the error for the hardware counters now.

**Comment by ikalchev** [comment]
So the hardware counters example fails to open with:
```
Error: failed to open perf event

Caused by:
    No such file or directory (os error 2)
```

Reading on "the net" got me to check:

```\$ perf list hw
List of pre-defined events (to be used in -e or -M):
<nothing>
```
I guess the VM doesn't have hw counters, which can make sense I guess.

That aside, my previous comment was not quite correct - turns out that most of the times the probe doesn't seem to be called at all. In very few occasions I can see debug traces in `/sys/kernel/debug/tracing/trace_pipe`. I tried to play around with the frequency and attach to each cpu explicitly, but to no avail.

**Comment by ikalchev** [comment]
As this is a user setup issue, closing the issue. Thanks for the comments!
