### ISSUE TITLE
Update libbpf (C) in libbpf-{rs,sys} cargo crate to 1.3.0

### ISSUE THREAD

**Issue by telbizov** [libbpf/libbpf-rs#654]
Hello folks,

Apologies if there's a better way to report this, but I am new to rust and libbpf-rs so please redirect me appropriately.

I'm rewriting part of a project from C to Rust and trying to use libbpf-rs for the userland components. I installed `libbpf-rs = "0.22.1"` via cargo and I noticed that it packages libbpf (C) in itself. However, it seems like it carries version 1.2 while latest version is 1.3.0.

I was wondering if it would be possible to upgrade the crate to the latest 1.3.0?

Example failure that I encountered is that programs with the new SEC("tc/ingress") are rejected while the older SEC("tc") syntax is still supported.

Thank you in advance,
Rumen Telbizov

**Comment by danielocfb** [comment]
Such an update has been done as part of https://github.com/libbpf/libbpf-sys/pull/72. Alas, the maintainer is non-responsive to [asks](https://github.com/libbpf/libbpf-sys/pull/74#issuecomment-1870490924) for a new release.

cc @anakryiko who may have permissions to cut a new release as well

**Comment by danielocfb** [comment]
That being said, you can always use a system libbpf or [consume](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#working-with-an-unpublished-minor-version) `libbpf-sys` from the respective tree.

**Comment by anakryiko** [comment]
> cc @anakryiko who may have permissions to cut a new release as well

I pinged Alex just now, hopefully he'll cut a release soon.

**Comment by telbizov** [comment]
Thanks @anakryiko !

**Comment by danielocfb** [comment]
[`libbpf-sys v1.3.0+v1.3.0`](https://crates.io/crates/libbpf-sys/1.3.0+v1.3.0) has been published.

**Comment by telbizov** [comment]
Tested on my end and confirmed that it works as expected.

Appreciate your help @danielocfb and @anakryiko !
