### ISSUE TITLE
Update libbpf-sys to latest release

### ISSUE THREAD

**Issue by syogaraj** [libbpf/libbpf-rs#658]
From libbpf-rs's `Cargo.toml`, the libbpf-sys version is `1.0.3` whereas the current libbpf-sys release is `1.3.0`.
Shall we update the libbpf-sys version or Are there any issues in updating it to the latest one?

Note: Noticed a PR (#306) that reverted an update for libbpf-sys version in the past. Hence want to confirm it.

**Comment by danielocfb** [comment]
We should not. Please read through the PR for the explanation.
