### ISSUE TITLE
rustfmt binary dependency not explicit

### ISSUE THREAD

**Issue by bentiss** [libbpf/libbpf-rs#68]
Since the inclusion of the generation of the skeleton, I was not able to use `cargo libbpf make`, even in the example folder of a plain git clone of the project.

My problem was that `rustfmt` was not part of the default install on Fedora, and so the generation of the skeleton failed. The problem is the error message is not very explicit.

For a reproducer and the output, see the following:
```bash
$> podman run --rm -ti fedora:33
[root@434ed7ebb708 /]# cd
[root@434ed7ebb708 ~]# dnf install -y cargo git clang llvm zlib-devel libbpf-devel
[root@434ed7ebb708 ~]# git clone https://github.com/libbpf/libbpf-rs.git
[root@434ed7ebb708 ~]# cd libbpf-rs/examples/runqslower/
[root@434ed7ebb708 runqslower]# cargo install libbpf-cargo
[root@434ed7ebb708 runqslower]# export PATH=/root/.cargo/bin:$PATH
[root@434ed7ebb708 runqslower]# cargo libbpf make
Compiling BPF objects
Generating skeletons
libbpf: elf: skipping unrecognized data section(25) .eh_frame
libbpf: elf: skipping relo section(26) .rel.eh_frame for section(25) .eh_frame
libbpf: elf: skipping unrecognized data section(25) .eh_frame
libbpf: elf: skipping relo section(26) .rel.eh_frame for section(25) .eh_frame
Warning: unrecognized map: .maps
Warning: unrecognized map: license
Failed to generate skeleton for /root/libbpf-rs/examples/runqslower/src/bpf/runqslower.bpf.c: No such file or directory (os error 2)
Failed to generate skeletons
```

So today, I took `rust-gdb` and traced down why it wouldn't open `/root/libbpf-rs/examples/runqslower/src/bpf/runqslower.bpf.c` while it is obviously there. And it turns out that the `os error 2` is not related to this file, but because of https://github.com/libbpf/libbpf-rs/blob/master/libbpf-cargo/src/gen.rs#L767:

```rust
let skel = rustfmt(&gen_skel_contents(debug, name, obj)?, rustfmt_path)?;
```

I am very much a novice in rust, so it was not immediate to me that this was trying to access `rustfmt`, and external binary.

It would be good if we could either have a detection of this problem earlier, or even a dependency on `rustfmt` when installing `libbpf-cargo`.

Thanks!

**Comment by danobi** [comment]
Thanks for the bug report and sorry about the bad error message.

IMO this feels like a fedora issue to me, I consider `rustfmt` to be a standard part of development tools. For example, `cargo fmt` will call out to `rustfmt` (which in my mind implies `cargo` depends on `rustfmt`).

**Comment by bentiss** [comment]
No need to apologies. I understand this might be a fedora packaging issue, and I appreciate your quick PR to make the error message much more explicit. Thanks!

**Comment by jirutka** [comment]
Nope, it’s not a Fedora packaging issue, `rustfmt` may not be available. It’s unexpected for a library to require `rustfmt` and since it should at least be mentioned in the readme.
