### ISSUE TITLE
Cannot build examples

### ISSUE THREAD

**Issue by vlad9486** [libbpf/libbpf-rs#70]
Try `cargo libbpf make --manifest-path examples/runqslower/Cargo.toml`

```
Compiling BPF objects
Failed to compile progs: Failed to compile obj=runqslower.bpf.o with status=exit code: 1
 stdout=
 
 stderr=
 /var/home/vladislav/workspace/vlad9486/libbpf-rs/examples/runqslower/src/bpf/runqslower.bpf.c:4:10: fatal error: 'bpf/bpf_helpers.h' file not found
#include <bpf/bpf_helpers.h>
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
```

I suppose [here](https://github.com/libbpf/libbpf-rs/blob/630752e5cadf1570ecb6846429ae21d3c023734e/libbpf-cargo/src/build.rs#L111) need to add `-I` option, but my system has no such header. I see out dir of `libbpf-sys` containing required header. But I cannot make clang see it.

**Comment by danobi** [comment]
On my system that header is installed by libbpf:
```
$ pacman -Qo /usr/include/bpf/bpf_helpers.h
/usr/include/bpf/bpf_helpers.h is owned by libbpf 0.3-1
```
Can you try installing libbpf?

**Comment by vlad9486** [comment]
@danobi Thank you for such quick help. It works.
