### ISSUE TITLE
Unable to run the example `runqslower`

### ISSUE THREAD

**Issue by chenbobby** [libbpf/libbpf-rs#724]
Hi, I am trying to run the [runqslower example](https://github.com/libbpf/libbpf-rs/tree/master/examples/runqslower) in a container on my MacBook Pro. However, I am getting an error on [the following line in main.rs](https://github.com/libbpf/libbpf-rs/blob/98932ee5c95dab8a723bd63c571ec8cbe4fbfed7/examples/runqslower/src/main.rs#L47):

```
if unsafe { libc::setrlimit(libc::RLIMIT_MEMLOCK, &rlimit) } != 0 {
```

With some extra `println!` debugging, I found that `ERRNO==libc::EPERM`, which indicates a permission issue. However, I am running the example in a non-root user with `sudo` privileges. **Why am I getting an `EPERM` error?**

<details>
<summary>View Environment Details</summary>

* Command: `cargo build && sudo ../../target/debug/runqslower 1000`
* OS: Ubuntu 22.04
* Linux Kernel Release: `5.15.49-linuxkit-pr`
* Machine Architecture: `aarch64`
* `uname -a`: `Linux 3fd71909e053 5.15.49-linuxkit-pr #1 SMP PREEMPT Thu May 25 07:27:39 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux`

</details>

**Comment by chenbobby** [comment]
Previously, I was running in a `ubuntu:22.04` Docker container ([link to image](https://hub.docker.com/layers/library/ubuntu/22.04/images/sha256-aa772c98400ef833586d1d517d3e8de670f7e712bf581ce6053165081773259d?context=explore)) using Docker Desktop on my MacBook Pro (M1 Pro).

I tried again on a [Vultr Cloud VM](https://www.vultr.com/) and it is working now.

I'm guessing that my original problem has to do with running in a Docker container. Closing this issue for now, but if anyone is able to get BPF working on a Linux container that is hosted by macOS, that would greatly save me some development costs.

**Comment by danobi** [comment]
Are you running the container with `--privileged`? 

Also maybe it's this? https://github.com/sudo-project/sudo/issues/42

**Comment by chenbobby** [comment]
@danobi Thanks for the tip! If I run the docker contianer using the flag `--privileged` and use the root user, then it works!

**Comment by chenbobby** [comment]
It also works with a non-root user with `sudo` privileges.
