### ISSUE TITLE
Feature request: looping over programs in loaded Object

### ISSUE THREAD

**Issue by rtkaratekid** [libbpf/libbpf-rs#77]
I think it would be really handy for non-CO-RE programs to have something like the libbpf function and macro that allows for looping over all the available programs in a BPF object. Currently I don't think the `progs` Vec is populated when an `Object` is created, so you _have_ to search for the program(s) by name. Because you have to know the program names ahead of time, you can't just load and attach programs generically.

I would guess that you could implement an iterator such that you could do the following code
```rust
for program in bpf_object.programs {
    // do something
 }
 ```
The iterator would just call `bpf_program__next` instead of trying to grab the next from the `progs` vec.

There might be some naming issues that would need to be addressed if you assume that the `progs` vec is empty by default though.

I thought about just implementing this and making a PR, but I want to see the receptiveness (since this library is "opinionated") and if any of the actual maintainers want to do this themselves.

**Comment by rtkaratekid** [comment]
Here's my naive and probably not so clean solution that might work. I haven't tested it but I might be able to get to it today.
object.rs
```rust
fn object_prog_next(
    obj: *const libbpf_sys::bpf_object,
    prog: *mut libbpf_sys::bpf_program, // needed to know what the next program is
) -> Result<Option<*mut libbpf_sys::bpf_program>> {
    let next_prog_ptr = unsafe { libbpf_sys::bpf_object__program_next(prog, obj) };
    Ok(util::ptr_to_option(next_prog_ptr))
}

pub struct Object {
    ptr: *mut libbpf_sys::bpf_object,
    curr_prog: *mut libbpf_sys::bpf_program,
    maps: HashMap<String, Map>,
    progs: HashMap<String, Program>,
}

impl Object {
    fn new(ptr: *mut libbpf_sys::bpf_object) -> Self {
        Object {
            ptr,
            curr_prog: std::ptr::null(), // null at initialization
            maps: HashMap::new(),
            progs: HashMap::new(),
        }
    }
  
> snip

impl Iterator for Object {

    pub fn next(&mut self) -> Result<Option<&mut Program>> {
        if let Some(next_prog_ptr) = object_prog_next(self.ptr, self.curr_prog)? {
            let title = unsafe { libbpf_sys::bpf_program__title(next_prog_ptr, false) };
            let err = unsafe { libbpf_sys::libbpf_get_error(title as *const _) };
            if err != 0 {
                return Err(Error::System(err as i32));
            }
            let section = util::c_ptr_to_string(title)?;

            Ok(Some(Program::new(ptr, section, section)))

        } else {
            Ok(None)
        }
    }

}
```

**Comment by danobi** [comment]
Seems reasonable to me. @anakryiko WDYT? I have a vague recollection of us discussing this at one point.

**Comment by rtkaratekid** [comment]
Okay sorry for spamming with comments, but I think having functions do this outside `new()` would be better. Then you can keep the `HashMap`s empty if you don't want to do that work prior to a user indicating they need it. If they do indicate they need it, you can set the struct's `HashMap` and return it. This is for programs but obviously this could be done for maps too.
```rust
    pub fn get_progs(&mut self) -> Result<&HashMap<String, Program>> {

        // if populated already return the populated hashmap
        if !self.progs.is_empty() {
            Ok(&self.progs)

        } else {
            // build the hashmap and then return it
            let mut progs: HashMap<String, Program> = HashMap::new();
            let mut prog: *mut libbpf_sys::bpf_program = std::ptr::null_mut();

            loop {
                // while there's another program to grab
                if let Some(next_prog_ptr) = object_prog_next(self.ptr, prog)? {

                    // get program name
                    let pname = unsafe { libbpf_sys::bpf_program__name(next_prog_ptr) };
                    let err = unsafe { libbpf_sys::libbpf_get_error(pname as *const _) };
                    if err != 0 {
                        std::process::exit(err as i32);
                    }

                    // get section title
                    let title = unsafe { libbpf_sys::bpf_program__title(next_prog_ptr, false) };
                    let err = unsafe { libbpf_sys::libbpf_get_error(title as *const _) };
                    if err != 0 {
                        std::process::exit(err as i32);
                    }

                    // convert to strings
                    let name = util::c_ptr_to_string(pname)?;
                    let section = util::c_ptr_to_string(title)?;

                    // push into progs
                    progs.insert(name.clone(), Program::new(next_prog_ptr, name, section));
                    prog = next_prog_ptr;

                } else {
                    break;
                }
            }

            self.progs = progs;

            Ok(&self.progs)
        }
    }
```
Then, to loop over the programs you'd just loop over the `HashMap` like any normal one. I'm not sure if the reference to the `HashMap` would impact the attaching of programs though.
```rust
for (prog_name, program) in obj.get_progs()? {
    // do something to each
}
```

**Comment by anakryiko** [comment]
Having ability to iterate BpfObject's maps and progs are obviously a good feature. Don't remember in what context we were discussing this, though, and if there are some Rust-specific gotchas there?

**Comment by danobi** [comment]
I don't think there are any gotchas. @rtkaratekid feel free to put up a PR -- will be easier to discuss the code there

**Comment by rtkaratekid** [comment]
I'll get one up today or tomorrow

**Comment by rtkaratekid** [comment]
PR submitted. I've got another PR I might submit soon regarding being able to define the `ctx` that is passed to the perf buffer opts when it's built. Makes it a bit easier to give context to callback functions.

**Comment by rtkaratekid** [comment]
Closing since there are two PRs addressing this #79 and #90
