### ISSUE TITLE
NULL key when using bpf_update_elem with BLOOM_FILTER

### ISSUE THREAD

**Issue by barthr** [libbpf/libbpf-rs#777]
Hi there,

Thanks for the great library. It has been a pleasure to use in writing my ebpf programs. Recently I did encounter an issue when using a BLOOM_FILTER. The docs state the following:

> A userspace program can add a value to a bloom filter using libbpf’s bpf_map_update_elem function. The key parameter must be set to NULL and flags must be set to BPF_ANY. Returns 0 on success, or negative error in case of failure.

However, it is not possible to pass NULL to this function with the current signature:
https://github.com/libbpf/libbpf-rs/blob/c10fffad7807ac0a03a8cf4fe9b76a4993b358af/libbpf-rs/src/map.rs#L777

Key has to be a slice to an u8 array. When passing in &[] it won't be able to add the value to the BLOOM_FILTER map. 

I did find the following code for generating the key:
https://github.com/libbpf/libbpf-rs/blob/c10fffad7807ac0a03a8cf4fe9b76a4993b358af/libbpf-rs/src/map.rs#L561-L567

I think this needs to be extended to also include BLOOM_FILTER. I can create a PR for that if you like.

**Comment by danielocfb** [comment]
Closed via 946feb5d841f734c86426a576bf0bc12417cdb85
