### ISSUE TITLE
Reduce boiler plate in libbpf-cargo tests

### ISSUE THREAD

**Issue by danobi** [libbpf/libbpf-rs#88]
Right now there's a bunch of integration tests in libbpf-cargo that have a huge amount of boiler plate. I think that could easily be reduced. Just scroll through the libbpf-cargo/src/test.rs and you'll see it.

**Comment by mimullin-bbry** [comment]
If this issue is not already being worked on, I can spend some cycles on it.

**Comment by danobi** [comment]
Don't believe it's being worked on yet. Would be much appreciated!

**Comment by mimullin-bbry** [comment]
Sorry that this took me so long to get a PR up.  I was very busy last week.
