### ISSUE TITLE
Possible mutation of `context_in` constant when using `test_run` in `syscall` methods

### ISSUE THREAD

**Issue by x1b6e6** [libbpf/libbpf-rs#888]
The field `context_in` in `ProgramInput` structure now looks like this::
```rust
struct ProgramInput<'dat> {
  context_in: Option<&'dat [u8]>,
  // ...
}
```

But this field can be overwritten by kernel when calling `syscall` method from bpf. [File `net/bpf/test_run.c` at line 1567](https://github.com/torvalds/linux/blob/defaf1a2113a22b00dfa1abc0fd2014820eaf065/net/bpf/test_run.c#L1567): kernel is copy back `context_in` to user space after calling `syscall`. And this is the only way to return some data from `syscall` (something bigger than `i32`).

Perhaps the `context_in` field should have the signature `Option<&'dat mut [u8]>` or special attention should be added to the comments of `test_run` method and `context_in` field.

Example of valid bpf code:
```c++
SEC("syscall")
int mySyscall(int *ctx) {
  *ctx += *ctx;
  return 0;
}
```
And rust with `libbpf-rs`:
```rust
let value: i32 = 21;
let mut value = value.to_ne_bytes();

let mut input = ProgramInput::default();
input.context_in = Some(&mut value);

mySyscall.test_run(input).unwrap();

let value = i32::from_ne_bytes(value);
assert_eq!(value, 42);
```

**Comment by danielocfb** [comment]
Hi @x1b6e6, yes, that's a fair point.

> Perhaps the context_in field should have the signature Option<&'dat mut [u8]>

Do you plan to send a pull request?

**Comment by x1b6e6** [comment]
> Do you plan to send a pull request?

If changing field signature is an acceptable solution then I can make this PR.
