### ISSUE TITLE
Unresolved import

### ISSUE THREAD

**Issue by k2enny** [libbpf/libbpf-rs#905]
error[E0432]: unresolved import `nix::fcntl`
  --> C:\Users\Shadow\.cargo\registry\src\index.crates.io-6f17d22bba15001f\libbpf-sys-1.4.3+v1.4.5\build.rs:11:5
   |
11 | use nix::fcntl;
   |     ^^^^^^^^^^ no `fcntl` in the root

when adding it to the Cargo.toml

**Comment by d-e-s-o** [comment]
If it says `libbpf-sys` then I'd recommend reporting it there. In general I doubt that Windows will be a supported target, ever.
