### ISSUE TITLE
[Libbpf-rs] Support context in sample_cb and lost_cb

### ISSUE THREAD

**Issue by mimullin-bbry** [libbpf/libbpf-rs#92]
Right now, sample_cb and lost_cb receive two parameters. (cpu: i32, data: &[u8]) and (cpu: i32, count: u64) respectively.

It would be useful to allow a user defined type as context such as a *mut, or a <T> such that
sample_cb(ctx: *mut, cpu: i32, data: &[u8])
or
sample_cb<T>(ctx: T, cpu: i32, data: &[u8])

**Comment by danobi** [comment]
Like a C-style context pointer to save some data in?

If so, better to use a capturing closure. We were very careful to design `PerfBuffer` and `RingBuffer` callbacks such that users can use capturing closures to store/access whatever data they need to process events.

**Comment by mimullin-bbry** [comment]
Forgive me for my C++ brain.  I might not understand how to do what I want in Rust.

What I am looking for is a way to pass into my sample_cb function two things.

1 - a structure to maintain state (which can be accomplished via globals in a thread_local!(), which is kinda dirty but gets the job done.

2 - various sides of a channel (I only need a single producer single consumer, but an std::thread::mpsc is what I'll be prototyping with).

Are you saying that I can setup up a closure and use it in PerfBufferBuilder::new().sample_cb() ?

If so, that's fantastic!

**Comment by danobi** [comment]
> 1 - a structure to maintain state (which can be accomplished via globals in a thread_local!(), which is kinda dirty but gets the job done.

You can use `Arc<Mutex<T>` pattern to share data between the callback and your main thread: https://doc.rust-lang.org/stable/std/sync/struct.Mutex.html#examples 

> 2 - various sides of a channel (I only need a single producer single consumer, but an std:thread:mpsc is what I'll be prototyping with).

Yes, see example here: https://github.com/libbpf/libbpf-rs/blob/8fcbba1bfc68b54ec24658cc41db93897a797e73/libbpf-rs/tests/test.rs#L501-L509
