### ISSUE TITLE
Mark Link with must_use

### ISSUE THREAD

**Issue by lbrndnr** [libbpf/libbpf-rs#940]
Hi,

I ran into an issue where my sockops program is immediately detached because I didn't actively ignore its link, as the following code shows:
```
skel.progs_mut()
    .sock_ops()
    .attach_cgroup(cgroup_fd)?;
```

Given that this problem is super easy to miss, would it make sense to mark `Link` with `must_use`? What do you think? :)

**Comment by danielocfb** [comment]
Yes, that's probably a good idea. Feel free to open a pull request. Thanks!

**Comment by d-e-s-o** [comment]
Closed by https://github.com/libbpf/libbpf-rs/commit/d97de7646b76bdd00216a28a3da6c2d7268e9261.
