### ISSUE TITLE
How to attach uprobe when a RingBuffer already holds an immutable reference to the skel?

### ISSUE THREAD

**Issue by guidao** [libbpf/libbpf-rs#953]
The pseudo code is as follows：
```rust
pub struct AgentSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::Object>,
        pub maps: AgentMaps<'obj>,
        pub progs: AgentProgs<'obj>,
        struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
        pub links: AgentLinks,
}

fn main() {
        let mut skel = // init AgentSkel
        let sched = PerfBufferBuilder::new(map).build()?;
       spawn(||{
       loop {
	    event_ringbuf.poll(Duration::from_micros(50))?;
	}
        })
	
      // In practice, this step is triggered by a event.
       skel.progs.uprobe.attach_uprobe(/xxxxx/);
}
```

**Comment by danielocfb** [comment]
I suspect we could make all attach methods work on a shared receiver, at least if the various function signatures are to be believed:
```
    pub fn bpf_program__attach(prog: *const bpf_program) -> *mut bpf_link;
```

Short of that, you can probably create an owned `MapHandle` and pass that to `PerfBufferBuilder` and then there would be no issue with exclusivity.

**Comment by guidao** [comment]
> I suspect we could make all attach methods work on a shared receiver, at least if the various function signatures are to be believed:
> 
> ```rust
>     pub fn bpf_program__attach(prog: *const bpf_program) -> *mut bpf_link;
> ```
> 
> Short of that, you can probably create an owned `MapHandle` and pass that to `PerfBufferBuilder` and then there would be no issue with exclusivity.

Got it. thanks~
