### ISSUE TITLE
uprobe overhead when specifying a pid

### ISSUE THREAD

**Issue by sebastiaoamaro** [libbpf/libbpf-rs#981]
Hi,
First of all, I don't know if this belongs here or if I should email it to the BPF mailing list. Please let me know.
I am using:
libbpf-cargo = "0.24.6"
libbpf-rs = "0.24.6"
libbpf-sys = "1.4.3"
On kernel 6.8.0-47-generic. 
I am attaching 252 uprobes to a system, these symbols are not regularly called (90ish times over 9 minutes), however, when I specify a pid the throughput drops **3 times** from 12k ops/sec to 4k ops/sec. When I do not specify a PID, and simply pass -1 the throughput remains the same (as it should, since 90 times is not significant to affect overhead I would say). It looks as if we are switching from userspace to kernel space without triggering the uprobe.

Do not know if this is a known issue, it does not look like an intended behavior.

**Comment by danielocfb** [comment]
I believe a bunch of speed ups to uprobes have landed in recent times. May be worth trying on a more recent kernel. Irrespective of that, I'd recommend inquiring with the BPF mailing list.
